// <auto-generated>
/*
 * Link API
 *
 * API pública de Link (Kiban): ejecuta un servicio de consulta/validación del catálogo Link (curp, sat, imss, nip, sms, buró de crédito, etc.), consulta su resultado y revisa el historial de ejecuciones.  Link expone un conjunto de endpoints genéricos: el servicio a ejecutar se elige en la ruta con {service}/{subservice}. El cuerpo de la petición y la forma de la respuesta dependen del servicio elegido; cada servicio define sus propios campos. Consulta el catálogo de servicios para el detalle de cada uno. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://link.kiban.com y sandbox en https://sandbox.link.kiban.com. En sandbox la ejecución no llama al proveedor real: devuelve un test case configurable, para que puedas integrar el contrato del servicio sin costo ni credenciales reales.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;

namespace kiban.sdk.link.Client
{
    /// <summary>
    /// API Exception
    /// </summary>
    public class ApiException : Exception
    {
        /// <summary>
        /// The reason the api request failed
        /// </summary>
        public string? ReasonPhrase { get; }

        /// <summary>
        /// The HttpStatusCode
        /// </summary>
        public System.Net.HttpStatusCode StatusCode { get; }

        /// <summary>
        /// The raw data returned by the api
        /// </summary>
        public string RawContent { get; }
        
        /// <summary>
        /// Construct the ApiException from parts of the response
        /// </summary>
        /// <param name="reasonPhrase"></param>
        /// <param name="statusCode"></param>
        /// <param name="rawContent"></param>
        public ApiException(string? reasonPhrase, System.Net.HttpStatusCode statusCode, string rawContent) : base(reasonPhrase ?? rawContent)
        {
            ReasonPhrase = reasonPhrase;

            StatusCode = statusCode;

            RawContent = rawContent;
        }
    }
}
