// <auto-generated>
/*
 * Link API
 *
 * API pública de Link (Kiban): ejecuta un servicio de consulta/validación del catálogo Link (curp, sat, imss, nip, sms, buró de crédito, etc.), consulta su resultado y revisa el historial de ejecuciones.  Link expone un conjunto de endpoints genéricos: el servicio a ejecutar se elige en la ruta con {service}/{subservice}. El cuerpo de la petición y la forma de la respuesta dependen del servicio elegido; cada servicio define sus propios campos. Consulta el catálogo de servicios para el detalle de cada uno. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://link.kiban.com y sandbox en https://sandbox.link.kiban.com. En sandbox la ejecución no llama al proveedor real: devuelve un test case configurable, para que puedas integrar el contrato del servicio sin costo ni credenciales reales.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */
#nullable enable

using System;
using System.Linq;
using System.Collections.Generic;
using kiban.sdk.link.Client;

namespace kiban.sdk.link
{
    /// <summary>
    /// A class which will provide tokens.
    /// </summary>
    public abstract class TokenProvider<TTokenBase> where TTokenBase : TokenBase
    {
        /// <summary>
        /// Gets a token asynchronously for the specified header.
        /// </summary>
        /// <param name="header">The header name to retrieve a token for. Empty string for non-API-key authentication schemes.</param>
        /// <param name="cancellation">Cancellation token for the asynchronous operation.</param>
        /// <returns>A task that returns the requested token.</returns>
        protected internal abstract System.Threading.Tasks.ValueTask<TTokenBase> GetAsync(string header = "", System.Threading.CancellationToken cancellation = default);
    }
}