/*
Workfloo API

API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package workfloo

import (
	"encoding/json"
)

// checks if the ControllerPoolModelExecuteResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ControllerPoolModelExecuteResponse{}

// ControllerPoolModelExecuteResponse struct for ControllerPoolModelExecuteResponse
type ControllerPoolModelExecuteResponse struct {
	IdWorkfloo *string `json:"idWorkfloo,omitempty"`
	IdWorkflooDefinition *string `json:"idWorkflooDefinition,omitempty"`
}

// NewControllerPoolModelExecuteResponse instantiates a new ControllerPoolModelExecuteResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewControllerPoolModelExecuteResponse() *ControllerPoolModelExecuteResponse {
	this := ControllerPoolModelExecuteResponse{}
	return &this
}

// NewControllerPoolModelExecuteResponseWithDefaults instantiates a new ControllerPoolModelExecuteResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewControllerPoolModelExecuteResponseWithDefaults() *ControllerPoolModelExecuteResponse {
	this := ControllerPoolModelExecuteResponse{}
	return &this
}

// GetIdWorkfloo returns the IdWorkfloo field value if set, zero value otherwise.
func (o *ControllerPoolModelExecuteResponse) GetIdWorkfloo() string {
	if o == nil || IsNil(o.IdWorkfloo) {
		var ret string
		return ret
	}
	return *o.IdWorkfloo
}

// GetIdWorkflooOk returns a tuple with the IdWorkfloo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerPoolModelExecuteResponse) GetIdWorkflooOk() (*string, bool) {
	if o == nil || IsNil(o.IdWorkfloo) {
		return nil, false
	}
	return o.IdWorkfloo, true
}

// HasIdWorkfloo returns a boolean if a field has been set.
func (o *ControllerPoolModelExecuteResponse) HasIdWorkfloo() bool {
	if o != nil && !IsNil(o.IdWorkfloo) {
		return true
	}

	return false
}

// SetIdWorkfloo gets a reference to the given string and assigns it to the IdWorkfloo field.
func (o *ControllerPoolModelExecuteResponse) SetIdWorkfloo(v string) {
	o.IdWorkfloo = &v
}

// GetIdWorkflooDefinition returns the IdWorkflooDefinition field value if set, zero value otherwise.
func (o *ControllerPoolModelExecuteResponse) GetIdWorkflooDefinition() string {
	if o == nil || IsNil(o.IdWorkflooDefinition) {
		var ret string
		return ret
	}
	return *o.IdWorkflooDefinition
}

// GetIdWorkflooDefinitionOk returns a tuple with the IdWorkflooDefinition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerPoolModelExecuteResponse) GetIdWorkflooDefinitionOk() (*string, bool) {
	if o == nil || IsNil(o.IdWorkflooDefinition) {
		return nil, false
	}
	return o.IdWorkflooDefinition, true
}

// HasIdWorkflooDefinition returns a boolean if a field has been set.
func (o *ControllerPoolModelExecuteResponse) HasIdWorkflooDefinition() bool {
	if o != nil && !IsNil(o.IdWorkflooDefinition) {
		return true
	}

	return false
}

// SetIdWorkflooDefinition gets a reference to the given string and assigns it to the IdWorkflooDefinition field.
func (o *ControllerPoolModelExecuteResponse) SetIdWorkflooDefinition(v string) {
	o.IdWorkflooDefinition = &v
}

func (o ControllerPoolModelExecuteResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ControllerPoolModelExecuteResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IdWorkfloo) {
		toSerialize["idWorkfloo"] = o.IdWorkfloo
	}
	if !IsNil(o.IdWorkflooDefinition) {
		toSerialize["idWorkflooDefinition"] = o.IdWorkflooDefinition
	}
	return toSerialize, nil
}

type NullableControllerPoolModelExecuteResponse struct {
	value *ControllerPoolModelExecuteResponse
	isSet bool
}

func (v NullableControllerPoolModelExecuteResponse) Get() *ControllerPoolModelExecuteResponse {
	return v.value
}

func (v *NullableControllerPoolModelExecuteResponse) Set(val *ControllerPoolModelExecuteResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableControllerPoolModelExecuteResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableControllerPoolModelExecuteResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableControllerPoolModelExecuteResponse(val *ControllerPoolModelExecuteResponse) *NullableControllerPoolModelExecuteResponse {
	return &NullableControllerPoolModelExecuteResponse{value: val, isSet: true}
}

func (v NullableControllerPoolModelExecuteResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableControllerPoolModelExecuteResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


