/*
Workfloo API

API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package workfloo

import (
	"encoding/json"
)

// checks if the ControllerWorkflooModelReviewResume type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ControllerWorkflooModelReviewResume{}

// ControllerWorkflooModelReviewResume struct for ControllerWorkflooModelReviewResume
type ControllerWorkflooModelReviewResume struct {
	FieldId *string `json:"fieldId,omitempty"`
	Message *string `json:"message,omitempty"`
	SourceNodeId *string `json:"sourceNodeId,omitempty"`
}

// NewControllerWorkflooModelReviewResume instantiates a new ControllerWorkflooModelReviewResume object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewControllerWorkflooModelReviewResume() *ControllerWorkflooModelReviewResume {
	this := ControllerWorkflooModelReviewResume{}
	return &this
}

// NewControllerWorkflooModelReviewResumeWithDefaults instantiates a new ControllerWorkflooModelReviewResume object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewControllerWorkflooModelReviewResumeWithDefaults() *ControllerWorkflooModelReviewResume {
	this := ControllerWorkflooModelReviewResume{}
	return &this
}

// GetFieldId returns the FieldId field value if set, zero value otherwise.
func (o *ControllerWorkflooModelReviewResume) GetFieldId() string {
	if o == nil || IsNil(o.FieldId) {
		var ret string
		return ret
	}
	return *o.FieldId
}

// GetFieldIdOk returns a tuple with the FieldId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerWorkflooModelReviewResume) GetFieldIdOk() (*string, bool) {
	if o == nil || IsNil(o.FieldId) {
		return nil, false
	}
	return o.FieldId, true
}

// HasFieldId returns a boolean if a field has been set.
func (o *ControllerWorkflooModelReviewResume) HasFieldId() bool {
	if o != nil && !IsNil(o.FieldId) {
		return true
	}

	return false
}

// SetFieldId gets a reference to the given string and assigns it to the FieldId field.
func (o *ControllerWorkflooModelReviewResume) SetFieldId(v string) {
	o.FieldId = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ControllerWorkflooModelReviewResume) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerWorkflooModelReviewResume) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ControllerWorkflooModelReviewResume) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ControllerWorkflooModelReviewResume) SetMessage(v string) {
	o.Message = &v
}

// GetSourceNodeId returns the SourceNodeId field value if set, zero value otherwise.
func (o *ControllerWorkflooModelReviewResume) GetSourceNodeId() string {
	if o == nil || IsNil(o.SourceNodeId) {
		var ret string
		return ret
	}
	return *o.SourceNodeId
}

// GetSourceNodeIdOk returns a tuple with the SourceNodeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerWorkflooModelReviewResume) GetSourceNodeIdOk() (*string, bool) {
	if o == nil || IsNil(o.SourceNodeId) {
		return nil, false
	}
	return o.SourceNodeId, true
}

// HasSourceNodeId returns a boolean if a field has been set.
func (o *ControllerWorkflooModelReviewResume) HasSourceNodeId() bool {
	if o != nil && !IsNil(o.SourceNodeId) {
		return true
	}

	return false
}

// SetSourceNodeId gets a reference to the given string and assigns it to the SourceNodeId field.
func (o *ControllerWorkflooModelReviewResume) SetSourceNodeId(v string) {
	o.SourceNodeId = &v
}

func (o ControllerWorkflooModelReviewResume) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ControllerWorkflooModelReviewResume) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FieldId) {
		toSerialize["fieldId"] = o.FieldId
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.SourceNodeId) {
		toSerialize["sourceNodeId"] = o.SourceNodeId
	}
	return toSerialize, nil
}

type NullableControllerWorkflooModelReviewResume struct {
	value *ControllerWorkflooModelReviewResume
	isSet bool
}

func (v NullableControllerWorkflooModelReviewResume) Get() *ControllerWorkflooModelReviewResume {
	return v.value
}

func (v *NullableControllerWorkflooModelReviewResume) Set(val *ControllerWorkflooModelReviewResume) {
	v.value = val
	v.isSet = true
}

func (v NullableControllerWorkflooModelReviewResume) IsSet() bool {
	return v.isSet
}

func (v *NullableControllerWorkflooModelReviewResume) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableControllerWorkflooModelReviewResume(val *ControllerWorkflooModelReviewResume) *NullableControllerWorkflooModelReviewResume {
	return &NullableControllerWorkflooModelReviewResume{value: val, isSet: true}
}

func (v NullableControllerWorkflooModelReviewResume) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableControllerWorkflooModelReviewResume) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


