/*
Workfloo API

API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package workfloo

import (
	"encoding/json"
)

// checks if the ControllerWorkflooModelApiHttp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ControllerWorkflooModelApiHttp{}

// ControllerWorkflooModelApiHttp struct for ControllerWorkflooModelApiHttp
type ControllerWorkflooModelApiHttp struct {
	Body []int32 `json:"body,omitempty"`
	Date *string `json:"date,omitempty"`
	Headers *map[string]string `json:"headers,omitempty"`
	HttpCode *int32 `json:"httpCode,omitempty"`
	QueryParams *map[string]string `json:"queryParams,omitempty"`
}

// NewControllerWorkflooModelApiHttp instantiates a new ControllerWorkflooModelApiHttp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewControllerWorkflooModelApiHttp() *ControllerWorkflooModelApiHttp {
	this := ControllerWorkflooModelApiHttp{}
	return &this
}

// NewControllerWorkflooModelApiHttpWithDefaults instantiates a new ControllerWorkflooModelApiHttp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewControllerWorkflooModelApiHttpWithDefaults() *ControllerWorkflooModelApiHttp {
	this := ControllerWorkflooModelApiHttp{}
	return &this
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *ControllerWorkflooModelApiHttp) GetBody() []int32 {
	if o == nil || IsNil(o.Body) {
		var ret []int32
		return ret
	}
	return o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerWorkflooModelApiHttp) GetBodyOk() ([]int32, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *ControllerWorkflooModelApiHttp) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given []int32 and assigns it to the Body field.
func (o *ControllerWorkflooModelApiHttp) SetBody(v []int32) {
	o.Body = v
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *ControllerWorkflooModelApiHttp) GetDate() string {
	if o == nil || IsNil(o.Date) {
		var ret string
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerWorkflooModelApiHttp) GetDateOk() (*string, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *ControllerWorkflooModelApiHttp) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given string and assigns it to the Date field.
func (o *ControllerWorkflooModelApiHttp) SetDate(v string) {
	o.Date = &v
}

// GetHeaders returns the Headers field value if set, zero value otherwise.
func (o *ControllerWorkflooModelApiHttp) GetHeaders() map[string]string {
	if o == nil || IsNil(o.Headers) {
		var ret map[string]string
		return ret
	}
	return *o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerWorkflooModelApiHttp) GetHeadersOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Headers) {
		return nil, false
	}
	return o.Headers, true
}

// HasHeaders returns a boolean if a field has been set.
func (o *ControllerWorkflooModelApiHttp) HasHeaders() bool {
	if o != nil && !IsNil(o.Headers) {
		return true
	}

	return false
}

// SetHeaders gets a reference to the given map[string]string and assigns it to the Headers field.
func (o *ControllerWorkflooModelApiHttp) SetHeaders(v map[string]string) {
	o.Headers = &v
}

// GetHttpCode returns the HttpCode field value if set, zero value otherwise.
func (o *ControllerWorkflooModelApiHttp) GetHttpCode() int32 {
	if o == nil || IsNil(o.HttpCode) {
		var ret int32
		return ret
	}
	return *o.HttpCode
}

// GetHttpCodeOk returns a tuple with the HttpCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerWorkflooModelApiHttp) GetHttpCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.HttpCode) {
		return nil, false
	}
	return o.HttpCode, true
}

// HasHttpCode returns a boolean if a field has been set.
func (o *ControllerWorkflooModelApiHttp) HasHttpCode() bool {
	if o != nil && !IsNil(o.HttpCode) {
		return true
	}

	return false
}

// SetHttpCode gets a reference to the given int32 and assigns it to the HttpCode field.
func (o *ControllerWorkflooModelApiHttp) SetHttpCode(v int32) {
	o.HttpCode = &v
}

// GetQueryParams returns the QueryParams field value if set, zero value otherwise.
func (o *ControllerWorkflooModelApiHttp) GetQueryParams() map[string]string {
	if o == nil || IsNil(o.QueryParams) {
		var ret map[string]string
		return ret
	}
	return *o.QueryParams
}

// GetQueryParamsOk returns a tuple with the QueryParams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerWorkflooModelApiHttp) GetQueryParamsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.QueryParams) {
		return nil, false
	}
	return o.QueryParams, true
}

// HasQueryParams returns a boolean if a field has been set.
func (o *ControllerWorkflooModelApiHttp) HasQueryParams() bool {
	if o != nil && !IsNil(o.QueryParams) {
		return true
	}

	return false
}

// SetQueryParams gets a reference to the given map[string]string and assigns it to the QueryParams field.
func (o *ControllerWorkflooModelApiHttp) SetQueryParams(v map[string]string) {
	o.QueryParams = &v
}

func (o ControllerWorkflooModelApiHttp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ControllerWorkflooModelApiHttp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	if !IsNil(o.Headers) {
		toSerialize["headers"] = o.Headers
	}
	if !IsNil(o.HttpCode) {
		toSerialize["httpCode"] = o.HttpCode
	}
	if !IsNil(o.QueryParams) {
		toSerialize["queryParams"] = o.QueryParams
	}
	return toSerialize, nil
}

type NullableControllerWorkflooModelApiHttp struct {
	value *ControllerWorkflooModelApiHttp
	isSet bool
}

func (v NullableControllerWorkflooModelApiHttp) Get() *ControllerWorkflooModelApiHttp {
	return v.value
}

func (v *NullableControllerWorkflooModelApiHttp) Set(val *ControllerWorkflooModelApiHttp) {
	v.value = val
	v.isSet = true
}

func (v NullableControllerWorkflooModelApiHttp) IsSet() bool {
	return v.isSet
}

func (v *NullableControllerWorkflooModelApiHttp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableControllerWorkflooModelApiHttp(val *ControllerWorkflooModelApiHttp) *NullableControllerWorkflooModelApiHttp {
	return &NullableControllerWorkflooModelApiHttp{value: val, isSet: true}
}

func (v NullableControllerWorkflooModelApiHttp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableControllerWorkflooModelApiHttp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


