/*
Workfloo API

API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package workfloo

import (
	"encoding/json"
)

// checks if the ControllerWorkflooDefinitionModelFormFieldSection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ControllerWorkflooDefinitionModelFormFieldSection{}

// ControllerWorkflooDefinitionModelFormFieldSection struct for ControllerWorkflooDefinitionModelFormFieldSection
type ControllerWorkflooDefinitionModelFormFieldSection struct {
	Fields []ControllerWorkflooDefinitionModelField `json:"fields,omitempty"`
	Section *string `json:"section,omitempty"`
}

// NewControllerWorkflooDefinitionModelFormFieldSection instantiates a new ControllerWorkflooDefinitionModelFormFieldSection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewControllerWorkflooDefinitionModelFormFieldSection() *ControllerWorkflooDefinitionModelFormFieldSection {
	this := ControllerWorkflooDefinitionModelFormFieldSection{}
	return &this
}

// NewControllerWorkflooDefinitionModelFormFieldSectionWithDefaults instantiates a new ControllerWorkflooDefinitionModelFormFieldSection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewControllerWorkflooDefinitionModelFormFieldSectionWithDefaults() *ControllerWorkflooDefinitionModelFormFieldSection {
	this := ControllerWorkflooDefinitionModelFormFieldSection{}
	return &this
}

// GetFields returns the Fields field value if set, zero value otherwise.
func (o *ControllerWorkflooDefinitionModelFormFieldSection) GetFields() []ControllerWorkflooDefinitionModelField {
	if o == nil || IsNil(o.Fields) {
		var ret []ControllerWorkflooDefinitionModelField
		return ret
	}
	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerWorkflooDefinitionModelFormFieldSection) GetFieldsOk() ([]ControllerWorkflooDefinitionModelField, bool) {
	if o == nil || IsNil(o.Fields) {
		return nil, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *ControllerWorkflooDefinitionModelFormFieldSection) HasFields() bool {
	if o != nil && !IsNil(o.Fields) {
		return true
	}

	return false
}

// SetFields gets a reference to the given []ControllerWorkflooDefinitionModelField and assigns it to the Fields field.
func (o *ControllerWorkflooDefinitionModelFormFieldSection) SetFields(v []ControllerWorkflooDefinitionModelField) {
	o.Fields = v
}

// GetSection returns the Section field value if set, zero value otherwise.
func (o *ControllerWorkflooDefinitionModelFormFieldSection) GetSection() string {
	if o == nil || IsNil(o.Section) {
		var ret string
		return ret
	}
	return *o.Section
}

// GetSectionOk returns a tuple with the Section field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerWorkflooDefinitionModelFormFieldSection) GetSectionOk() (*string, bool) {
	if o == nil || IsNil(o.Section) {
		return nil, false
	}
	return o.Section, true
}

// HasSection returns a boolean if a field has been set.
func (o *ControllerWorkflooDefinitionModelFormFieldSection) HasSection() bool {
	if o != nil && !IsNil(o.Section) {
		return true
	}

	return false
}

// SetSection gets a reference to the given string and assigns it to the Section field.
func (o *ControllerWorkflooDefinitionModelFormFieldSection) SetSection(v string) {
	o.Section = &v
}

func (o ControllerWorkflooDefinitionModelFormFieldSection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ControllerWorkflooDefinitionModelFormFieldSection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Fields) {
		toSerialize["fields"] = o.Fields
	}
	if !IsNil(o.Section) {
		toSerialize["section"] = o.Section
	}
	return toSerialize, nil
}

type NullableControllerWorkflooDefinitionModelFormFieldSection struct {
	value *ControllerWorkflooDefinitionModelFormFieldSection
	isSet bool
}

func (v NullableControllerWorkflooDefinitionModelFormFieldSection) Get() *ControllerWorkflooDefinitionModelFormFieldSection {
	return v.value
}

func (v *NullableControllerWorkflooDefinitionModelFormFieldSection) Set(val *ControllerWorkflooDefinitionModelFormFieldSection) {
	v.value = val
	v.isSet = true
}

func (v NullableControllerWorkflooDefinitionModelFormFieldSection) IsSet() bool {
	return v.isSet
}

func (v *NullableControllerWorkflooDefinitionModelFormFieldSection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableControllerWorkflooDefinitionModelFormFieldSection(val *ControllerWorkflooDefinitionModelFormFieldSection) *NullableControllerWorkflooDefinitionModelFormFieldSection {
	return &NullableControllerWorkflooDefinitionModelFormFieldSection{value: val, isSet: true}
}

func (v NullableControllerWorkflooDefinitionModelFormFieldSection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableControllerWorkflooDefinitionModelFormFieldSection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


