/*
Workfloo API

API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package workfloo

import (
	"encoding/json"
)

// checks if the ControllerWorkflooDefinitionModelAutoFilledBy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ControllerWorkflooDefinitionModelAutoFilledBy{}

// ControllerWorkflooDefinitionModelAutoFilledBy struct for ControllerWorkflooDefinitionModelAutoFilledBy
type ControllerWorkflooDefinitionModelAutoFilledBy struct {
	NameNode *string `json:"nameNode,omitempty"`
	NodeId *string `json:"nodeId,omitempty"`
}

// NewControllerWorkflooDefinitionModelAutoFilledBy instantiates a new ControllerWorkflooDefinitionModelAutoFilledBy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewControllerWorkflooDefinitionModelAutoFilledBy() *ControllerWorkflooDefinitionModelAutoFilledBy {
	this := ControllerWorkflooDefinitionModelAutoFilledBy{}
	return &this
}

// NewControllerWorkflooDefinitionModelAutoFilledByWithDefaults instantiates a new ControllerWorkflooDefinitionModelAutoFilledBy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewControllerWorkflooDefinitionModelAutoFilledByWithDefaults() *ControllerWorkflooDefinitionModelAutoFilledBy {
	this := ControllerWorkflooDefinitionModelAutoFilledBy{}
	return &this
}

// GetNameNode returns the NameNode field value if set, zero value otherwise.
func (o *ControllerWorkflooDefinitionModelAutoFilledBy) GetNameNode() string {
	if o == nil || IsNil(o.NameNode) {
		var ret string
		return ret
	}
	return *o.NameNode
}

// GetNameNodeOk returns a tuple with the NameNode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerWorkflooDefinitionModelAutoFilledBy) GetNameNodeOk() (*string, bool) {
	if o == nil || IsNil(o.NameNode) {
		return nil, false
	}
	return o.NameNode, true
}

// HasNameNode returns a boolean if a field has been set.
func (o *ControllerWorkflooDefinitionModelAutoFilledBy) HasNameNode() bool {
	if o != nil && !IsNil(o.NameNode) {
		return true
	}

	return false
}

// SetNameNode gets a reference to the given string and assigns it to the NameNode field.
func (o *ControllerWorkflooDefinitionModelAutoFilledBy) SetNameNode(v string) {
	o.NameNode = &v
}

// GetNodeId returns the NodeId field value if set, zero value otherwise.
func (o *ControllerWorkflooDefinitionModelAutoFilledBy) GetNodeId() string {
	if o == nil || IsNil(o.NodeId) {
		var ret string
		return ret
	}
	return *o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerWorkflooDefinitionModelAutoFilledBy) GetNodeIdOk() (*string, bool) {
	if o == nil || IsNil(o.NodeId) {
		return nil, false
	}
	return o.NodeId, true
}

// HasNodeId returns a boolean if a field has been set.
func (o *ControllerWorkflooDefinitionModelAutoFilledBy) HasNodeId() bool {
	if o != nil && !IsNil(o.NodeId) {
		return true
	}

	return false
}

// SetNodeId gets a reference to the given string and assigns it to the NodeId field.
func (o *ControllerWorkflooDefinitionModelAutoFilledBy) SetNodeId(v string) {
	o.NodeId = &v
}

func (o ControllerWorkflooDefinitionModelAutoFilledBy) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ControllerWorkflooDefinitionModelAutoFilledBy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NameNode) {
		toSerialize["nameNode"] = o.NameNode
	}
	if !IsNil(o.NodeId) {
		toSerialize["nodeId"] = o.NodeId
	}
	return toSerialize, nil
}

type NullableControllerWorkflooDefinitionModelAutoFilledBy struct {
	value *ControllerWorkflooDefinitionModelAutoFilledBy
	isSet bool
}

func (v NullableControllerWorkflooDefinitionModelAutoFilledBy) Get() *ControllerWorkflooDefinitionModelAutoFilledBy {
	return v.value
}

func (v *NullableControllerWorkflooDefinitionModelAutoFilledBy) Set(val *ControllerWorkflooDefinitionModelAutoFilledBy) {
	v.value = val
	v.isSet = true
}

func (v NullableControllerWorkflooDefinitionModelAutoFilledBy) IsSet() bool {
	return v.isSet
}

func (v *NullableControllerWorkflooDefinitionModelAutoFilledBy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableControllerWorkflooDefinitionModelAutoFilledBy(val *ControllerWorkflooDefinitionModelAutoFilledBy) *NullableControllerWorkflooDefinitionModelAutoFilledBy {
	return &NullableControllerWorkflooDefinitionModelAutoFilledBy{value: val, isSet: true}
}

func (v NullableControllerWorkflooDefinitionModelAutoFilledBy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableControllerWorkflooDefinitionModelAutoFilledBy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


