/*
Workfloo API

API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package workfloo

import (
	"encoding/json"
)

// checks if the ControllerWorkflooModelValidationStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ControllerWorkflooModelValidationStatus{}

// ControllerWorkflooModelValidationStatus struct for ControllerWorkflooModelValidationStatus
type ControllerWorkflooModelValidationStatus struct {
	Fields []ControllerWorkflooModelValidationField `json:"fields,omitempty"`
	Instruction *string `json:"instruction,omitempty"`
	ReviewerNote *string `json:"reviewerNote,omitempty"`
	State *string `json:"state,omitempty"`
}

// NewControllerWorkflooModelValidationStatus instantiates a new ControllerWorkflooModelValidationStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewControllerWorkflooModelValidationStatus() *ControllerWorkflooModelValidationStatus {
	this := ControllerWorkflooModelValidationStatus{}
	return &this
}

// NewControllerWorkflooModelValidationStatusWithDefaults instantiates a new ControllerWorkflooModelValidationStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewControllerWorkflooModelValidationStatusWithDefaults() *ControllerWorkflooModelValidationStatus {
	this := ControllerWorkflooModelValidationStatus{}
	return &this
}

// GetFields returns the Fields field value if set, zero value otherwise.
func (o *ControllerWorkflooModelValidationStatus) GetFields() []ControllerWorkflooModelValidationField {
	if o == nil || IsNil(o.Fields) {
		var ret []ControllerWorkflooModelValidationField
		return ret
	}
	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerWorkflooModelValidationStatus) GetFieldsOk() ([]ControllerWorkflooModelValidationField, bool) {
	if o == nil || IsNil(o.Fields) {
		return nil, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *ControllerWorkflooModelValidationStatus) HasFields() bool {
	if o != nil && !IsNil(o.Fields) {
		return true
	}

	return false
}

// SetFields gets a reference to the given []ControllerWorkflooModelValidationField and assigns it to the Fields field.
func (o *ControllerWorkflooModelValidationStatus) SetFields(v []ControllerWorkflooModelValidationField) {
	o.Fields = v
}

// GetInstruction returns the Instruction field value if set, zero value otherwise.
func (o *ControllerWorkflooModelValidationStatus) GetInstruction() string {
	if o == nil || IsNil(o.Instruction) {
		var ret string
		return ret
	}
	return *o.Instruction
}

// GetInstructionOk returns a tuple with the Instruction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerWorkflooModelValidationStatus) GetInstructionOk() (*string, bool) {
	if o == nil || IsNil(o.Instruction) {
		return nil, false
	}
	return o.Instruction, true
}

// HasInstruction returns a boolean if a field has been set.
func (o *ControllerWorkflooModelValidationStatus) HasInstruction() bool {
	if o != nil && !IsNil(o.Instruction) {
		return true
	}

	return false
}

// SetInstruction gets a reference to the given string and assigns it to the Instruction field.
func (o *ControllerWorkflooModelValidationStatus) SetInstruction(v string) {
	o.Instruction = &v
}

// GetReviewerNote returns the ReviewerNote field value if set, zero value otherwise.
func (o *ControllerWorkflooModelValidationStatus) GetReviewerNote() string {
	if o == nil || IsNil(o.ReviewerNote) {
		var ret string
		return ret
	}
	return *o.ReviewerNote
}

// GetReviewerNoteOk returns a tuple with the ReviewerNote field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerWorkflooModelValidationStatus) GetReviewerNoteOk() (*string, bool) {
	if o == nil || IsNil(o.ReviewerNote) {
		return nil, false
	}
	return o.ReviewerNote, true
}

// HasReviewerNote returns a boolean if a field has been set.
func (o *ControllerWorkflooModelValidationStatus) HasReviewerNote() bool {
	if o != nil && !IsNil(o.ReviewerNote) {
		return true
	}

	return false
}

// SetReviewerNote gets a reference to the given string and assigns it to the ReviewerNote field.
func (o *ControllerWorkflooModelValidationStatus) SetReviewerNote(v string) {
	o.ReviewerNote = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *ControllerWorkflooModelValidationStatus) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerWorkflooModelValidationStatus) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *ControllerWorkflooModelValidationStatus) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *ControllerWorkflooModelValidationStatus) SetState(v string) {
	o.State = &v
}

func (o ControllerWorkflooModelValidationStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ControllerWorkflooModelValidationStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Fields) {
		toSerialize["fields"] = o.Fields
	}
	if !IsNil(o.Instruction) {
		toSerialize["instruction"] = o.Instruction
	}
	if !IsNil(o.ReviewerNote) {
		toSerialize["reviewerNote"] = o.ReviewerNote
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	return toSerialize, nil
}

type NullableControllerWorkflooModelValidationStatus struct {
	value *ControllerWorkflooModelValidationStatus
	isSet bool
}

func (v NullableControllerWorkflooModelValidationStatus) Get() *ControllerWorkflooModelValidationStatus {
	return v.value
}

func (v *NullableControllerWorkflooModelValidationStatus) Set(val *ControllerWorkflooModelValidationStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableControllerWorkflooModelValidationStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableControllerWorkflooModelValidationStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableControllerWorkflooModelValidationStatus(val *ControllerWorkflooModelValidationStatus) *NullableControllerWorkflooModelValidationStatus {
	return &NullableControllerWorkflooModelValidationStatus{value: val, isSet: true}
}

func (v NullableControllerWorkflooModelValidationStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableControllerWorkflooModelValidationStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


