/*
Workfloo API

API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package workfloo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ControllerWorkflooModelExecute type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ControllerWorkflooModelExecute{}

// ControllerWorkflooModelExecute struct for ControllerWorkflooModelExecute
type ControllerWorkflooModelExecute struct {
	CallbackUrl *string `json:"callbackUrl,omitempty"`
	CallbackXApiKey *string `json:"callbackXApiKey,omitempty"`
	Document map[string]interface{} `json:"document,omitempty"`
	Form map[string]interface{} `json:"form,omitempty"`
	IdWorkflooDefinition string `json:"idWorkflooDefinition"`
	ScenarioId *string `json:"scenarioId,omitempty"`
}

type _ControllerWorkflooModelExecute ControllerWorkflooModelExecute

// NewControllerWorkflooModelExecute instantiates a new ControllerWorkflooModelExecute object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewControllerWorkflooModelExecute(idWorkflooDefinition string) *ControllerWorkflooModelExecute {
	this := ControllerWorkflooModelExecute{}
	this.IdWorkflooDefinition = idWorkflooDefinition
	return &this
}

// NewControllerWorkflooModelExecuteWithDefaults instantiates a new ControllerWorkflooModelExecute object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewControllerWorkflooModelExecuteWithDefaults() *ControllerWorkflooModelExecute {
	this := ControllerWorkflooModelExecute{}
	return &this
}

// GetCallbackUrl returns the CallbackUrl field value if set, zero value otherwise.
func (o *ControllerWorkflooModelExecute) GetCallbackUrl() string {
	if o == nil || IsNil(o.CallbackUrl) {
		var ret string
		return ret
	}
	return *o.CallbackUrl
}

// GetCallbackUrlOk returns a tuple with the CallbackUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerWorkflooModelExecute) GetCallbackUrlOk() (*string, bool) {
	if o == nil || IsNil(o.CallbackUrl) {
		return nil, false
	}
	return o.CallbackUrl, true
}

// HasCallbackUrl returns a boolean if a field has been set.
func (o *ControllerWorkflooModelExecute) HasCallbackUrl() bool {
	if o != nil && !IsNil(o.CallbackUrl) {
		return true
	}

	return false
}

// SetCallbackUrl gets a reference to the given string and assigns it to the CallbackUrl field.
func (o *ControllerWorkflooModelExecute) SetCallbackUrl(v string) {
	o.CallbackUrl = &v
}

// GetCallbackXApiKey returns the CallbackXApiKey field value if set, zero value otherwise.
func (o *ControllerWorkflooModelExecute) GetCallbackXApiKey() string {
	if o == nil || IsNil(o.CallbackXApiKey) {
		var ret string
		return ret
	}
	return *o.CallbackXApiKey
}

// GetCallbackXApiKeyOk returns a tuple with the CallbackXApiKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerWorkflooModelExecute) GetCallbackXApiKeyOk() (*string, bool) {
	if o == nil || IsNil(o.CallbackXApiKey) {
		return nil, false
	}
	return o.CallbackXApiKey, true
}

// HasCallbackXApiKey returns a boolean if a field has been set.
func (o *ControllerWorkflooModelExecute) HasCallbackXApiKey() bool {
	if o != nil && !IsNil(o.CallbackXApiKey) {
		return true
	}

	return false
}

// SetCallbackXApiKey gets a reference to the given string and assigns it to the CallbackXApiKey field.
func (o *ControllerWorkflooModelExecute) SetCallbackXApiKey(v string) {
	o.CallbackXApiKey = &v
}

// GetDocument returns the Document field value if set, zero value otherwise.
func (o *ControllerWorkflooModelExecute) GetDocument() map[string]interface{} {
	if o == nil || IsNil(o.Document) {
		var ret map[string]interface{}
		return ret
	}
	return o.Document
}

// GetDocumentOk returns a tuple with the Document field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerWorkflooModelExecute) GetDocumentOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Document) {
		return map[string]interface{}{}, false
	}
	return o.Document, true
}

// HasDocument returns a boolean if a field has been set.
func (o *ControllerWorkflooModelExecute) HasDocument() bool {
	if o != nil && !IsNil(o.Document) {
		return true
	}

	return false
}

// SetDocument gets a reference to the given map[string]interface{} and assigns it to the Document field.
func (o *ControllerWorkflooModelExecute) SetDocument(v map[string]interface{}) {
	o.Document = v
}

// GetForm returns the Form field value if set, zero value otherwise.
func (o *ControllerWorkflooModelExecute) GetForm() map[string]interface{} {
	if o == nil || IsNil(o.Form) {
		var ret map[string]interface{}
		return ret
	}
	return o.Form
}

// GetFormOk returns a tuple with the Form field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerWorkflooModelExecute) GetFormOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Form) {
		return map[string]interface{}{}, false
	}
	return o.Form, true
}

// HasForm returns a boolean if a field has been set.
func (o *ControllerWorkflooModelExecute) HasForm() bool {
	if o != nil && !IsNil(o.Form) {
		return true
	}

	return false
}

// SetForm gets a reference to the given map[string]interface{} and assigns it to the Form field.
func (o *ControllerWorkflooModelExecute) SetForm(v map[string]interface{}) {
	o.Form = v
}

// GetIdWorkflooDefinition returns the IdWorkflooDefinition field value
func (o *ControllerWorkflooModelExecute) GetIdWorkflooDefinition() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IdWorkflooDefinition
}

// GetIdWorkflooDefinitionOk returns a tuple with the IdWorkflooDefinition field value
// and a boolean to check if the value has been set.
func (o *ControllerWorkflooModelExecute) GetIdWorkflooDefinitionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IdWorkflooDefinition, true
}

// SetIdWorkflooDefinition sets field value
func (o *ControllerWorkflooModelExecute) SetIdWorkflooDefinition(v string) {
	o.IdWorkflooDefinition = v
}

// GetScenarioId returns the ScenarioId field value if set, zero value otherwise.
func (o *ControllerWorkflooModelExecute) GetScenarioId() string {
	if o == nil || IsNil(o.ScenarioId) {
		var ret string
		return ret
	}
	return *o.ScenarioId
}

// GetScenarioIdOk returns a tuple with the ScenarioId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerWorkflooModelExecute) GetScenarioIdOk() (*string, bool) {
	if o == nil || IsNil(o.ScenarioId) {
		return nil, false
	}
	return o.ScenarioId, true
}

// HasScenarioId returns a boolean if a field has been set.
func (o *ControllerWorkflooModelExecute) HasScenarioId() bool {
	if o != nil && !IsNil(o.ScenarioId) {
		return true
	}

	return false
}

// SetScenarioId gets a reference to the given string and assigns it to the ScenarioId field.
func (o *ControllerWorkflooModelExecute) SetScenarioId(v string) {
	o.ScenarioId = &v
}

func (o ControllerWorkflooModelExecute) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ControllerWorkflooModelExecute) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CallbackUrl) {
		toSerialize["callbackUrl"] = o.CallbackUrl
	}
	if !IsNil(o.CallbackXApiKey) {
		toSerialize["callbackXApiKey"] = o.CallbackXApiKey
	}
	if !IsNil(o.Document) {
		toSerialize["document"] = o.Document
	}
	if !IsNil(o.Form) {
		toSerialize["form"] = o.Form
	}
	toSerialize["idWorkflooDefinition"] = o.IdWorkflooDefinition
	if !IsNil(o.ScenarioId) {
		toSerialize["scenarioId"] = o.ScenarioId
	}
	return toSerialize, nil
}

func (o *ControllerWorkflooModelExecute) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"idWorkflooDefinition",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varControllerWorkflooModelExecute := _ControllerWorkflooModelExecute{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varControllerWorkflooModelExecute)

	if err != nil {
		return err
	}

	*o = ControllerWorkflooModelExecute(varControllerWorkflooModelExecute)

	return err
}

type NullableControllerWorkflooModelExecute struct {
	value *ControllerWorkflooModelExecute
	isSet bool
}

func (v NullableControllerWorkflooModelExecute) Get() *ControllerWorkflooModelExecute {
	return v.value
}

func (v *NullableControllerWorkflooModelExecute) Set(val *ControllerWorkflooModelExecute) {
	v.value = val
	v.isSet = true
}

func (v NullableControllerWorkflooModelExecute) IsSet() bool {
	return v.isSet
}

func (v *NullableControllerWorkflooModelExecute) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableControllerWorkflooModelExecute(val *ControllerWorkflooModelExecute) *NullableControllerWorkflooModelExecute {
	return &NullableControllerWorkflooModelExecute{value: val, isSet: true}
}

func (v NullableControllerWorkflooModelExecute) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableControllerWorkflooModelExecute) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


