/*
Workfloo API

API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package workfloo

import (
	"encoding/json"
)

// checks if the ControllerWorkflooDefinitionModelForm type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ControllerWorkflooDefinitionModelForm{}

// ControllerWorkflooDefinitionModelForm struct for ControllerWorkflooDefinitionModelForm
type ControllerWorkflooDefinitionModelForm struct {
	FormFieldSection []ControllerWorkflooDefinitionModelFormFieldSection `json:"formFieldSection,omitempty"`
}

// NewControllerWorkflooDefinitionModelForm instantiates a new ControllerWorkflooDefinitionModelForm object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewControllerWorkflooDefinitionModelForm() *ControllerWorkflooDefinitionModelForm {
	this := ControllerWorkflooDefinitionModelForm{}
	return &this
}

// NewControllerWorkflooDefinitionModelFormWithDefaults instantiates a new ControllerWorkflooDefinitionModelForm object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewControllerWorkflooDefinitionModelFormWithDefaults() *ControllerWorkflooDefinitionModelForm {
	this := ControllerWorkflooDefinitionModelForm{}
	return &this
}

// GetFormFieldSection returns the FormFieldSection field value if set, zero value otherwise.
func (o *ControllerWorkflooDefinitionModelForm) GetFormFieldSection() []ControllerWorkflooDefinitionModelFormFieldSection {
	if o == nil || IsNil(o.FormFieldSection) {
		var ret []ControllerWorkflooDefinitionModelFormFieldSection
		return ret
	}
	return o.FormFieldSection
}

// GetFormFieldSectionOk returns a tuple with the FormFieldSection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerWorkflooDefinitionModelForm) GetFormFieldSectionOk() ([]ControllerWorkflooDefinitionModelFormFieldSection, bool) {
	if o == nil || IsNil(o.FormFieldSection) {
		return nil, false
	}
	return o.FormFieldSection, true
}

// HasFormFieldSection returns a boolean if a field has been set.
func (o *ControllerWorkflooDefinitionModelForm) HasFormFieldSection() bool {
	if o != nil && !IsNil(o.FormFieldSection) {
		return true
	}

	return false
}

// SetFormFieldSection gets a reference to the given []ControllerWorkflooDefinitionModelFormFieldSection and assigns it to the FormFieldSection field.
func (o *ControllerWorkflooDefinitionModelForm) SetFormFieldSection(v []ControllerWorkflooDefinitionModelFormFieldSection) {
	o.FormFieldSection = v
}

func (o ControllerWorkflooDefinitionModelForm) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ControllerWorkflooDefinitionModelForm) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FormFieldSection) {
		toSerialize["formFieldSection"] = o.FormFieldSection
	}
	return toSerialize, nil
}

type NullableControllerWorkflooDefinitionModelForm struct {
	value *ControllerWorkflooDefinitionModelForm
	isSet bool
}

func (v NullableControllerWorkflooDefinitionModelForm) Get() *ControllerWorkflooDefinitionModelForm {
	return v.value
}

func (v *NullableControllerWorkflooDefinitionModelForm) Set(val *ControllerWorkflooDefinitionModelForm) {
	v.value = val
	v.isSet = true
}

func (v NullableControllerWorkflooDefinitionModelForm) IsSet() bool {
	return v.isSet
}

func (v *NullableControllerWorkflooDefinitionModelForm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableControllerWorkflooDefinitionModelForm(val *ControllerWorkflooDefinitionModelForm) *NullableControllerWorkflooDefinitionModelForm {
	return &NullableControllerWorkflooDefinitionModelForm{value: val, isSet: true}
}

func (v NullableControllerWorkflooDefinitionModelForm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableControllerWorkflooDefinitionModelForm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


