/*
Workfloo API

API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package workfloo

import (
	"encoding/json"
)

// checks if the ControllerWorkflooModelLink type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ControllerWorkflooModelLink{}

// ControllerWorkflooModelLink struct for ControllerWorkflooModelLink
type ControllerWorkflooModelLink struct {
	Data map[string]interface{} `json:"data,omitempty"`
	Id *string `json:"id,omitempty"`
	Key *string `json:"key,omitempty"`
	Service *string `json:"service,omitempty"`
	SubService *string `json:"subService,omitempty"`
}

// NewControllerWorkflooModelLink instantiates a new ControllerWorkflooModelLink object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewControllerWorkflooModelLink() *ControllerWorkflooModelLink {
	this := ControllerWorkflooModelLink{}
	return &this
}

// NewControllerWorkflooModelLinkWithDefaults instantiates a new ControllerWorkflooModelLink object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewControllerWorkflooModelLinkWithDefaults() *ControllerWorkflooModelLink {
	this := ControllerWorkflooModelLink{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ControllerWorkflooModelLink) GetData() map[string]interface{} {
	if o == nil || IsNil(o.Data) {
		var ret map[string]interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerWorkflooModelLink) GetDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ControllerWorkflooModelLink) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *ControllerWorkflooModelLink) SetData(v map[string]interface{}) {
	o.Data = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ControllerWorkflooModelLink) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerWorkflooModelLink) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ControllerWorkflooModelLink) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ControllerWorkflooModelLink) SetId(v string) {
	o.Id = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *ControllerWorkflooModelLink) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerWorkflooModelLink) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *ControllerWorkflooModelLink) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *ControllerWorkflooModelLink) SetKey(v string) {
	o.Key = &v
}

// GetService returns the Service field value if set, zero value otherwise.
func (o *ControllerWorkflooModelLink) GetService() string {
	if o == nil || IsNil(o.Service) {
		var ret string
		return ret
	}
	return *o.Service
}

// GetServiceOk returns a tuple with the Service field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerWorkflooModelLink) GetServiceOk() (*string, bool) {
	if o == nil || IsNil(o.Service) {
		return nil, false
	}
	return o.Service, true
}

// HasService returns a boolean if a field has been set.
func (o *ControllerWorkflooModelLink) HasService() bool {
	if o != nil && !IsNil(o.Service) {
		return true
	}

	return false
}

// SetService gets a reference to the given string and assigns it to the Service field.
func (o *ControllerWorkflooModelLink) SetService(v string) {
	o.Service = &v
}

// GetSubService returns the SubService field value if set, zero value otherwise.
func (o *ControllerWorkflooModelLink) GetSubService() string {
	if o == nil || IsNil(o.SubService) {
		var ret string
		return ret
	}
	return *o.SubService
}

// GetSubServiceOk returns a tuple with the SubService field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerWorkflooModelLink) GetSubServiceOk() (*string, bool) {
	if o == nil || IsNil(o.SubService) {
		return nil, false
	}
	return o.SubService, true
}

// HasSubService returns a boolean if a field has been set.
func (o *ControllerWorkflooModelLink) HasSubService() bool {
	if o != nil && !IsNil(o.SubService) {
		return true
	}

	return false
}

// SetSubService gets a reference to the given string and assigns it to the SubService field.
func (o *ControllerWorkflooModelLink) SetSubService(v string) {
	o.SubService = &v
}

func (o ControllerWorkflooModelLink) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ControllerWorkflooModelLink) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Service) {
		toSerialize["service"] = o.Service
	}
	if !IsNil(o.SubService) {
		toSerialize["subService"] = o.SubService
	}
	return toSerialize, nil
}

type NullableControllerWorkflooModelLink struct {
	value *ControllerWorkflooModelLink
	isSet bool
}

func (v NullableControllerWorkflooModelLink) Get() *ControllerWorkflooModelLink {
	return v.value
}

func (v *NullableControllerWorkflooModelLink) Set(val *ControllerWorkflooModelLink) {
	v.value = val
	v.isSet = true
}

func (v NullableControllerWorkflooModelLink) IsSet() bool {
	return v.isSet
}

func (v *NullableControllerWorkflooModelLink) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableControllerWorkflooModelLink(val *ControllerWorkflooModelLink) *NullableControllerWorkflooModelLink {
	return &NullableControllerWorkflooModelLink{value: val, isSet: true}
}

func (v NullableControllerWorkflooModelLink) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableControllerWorkflooModelLink) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


