/*
 * Link API
 * API pública de Link (Kiban): ejecuta un servicio de consulta/validación del catálogo Link (curp, sat, imss, nip, sms, buró de crédito, etc.), consulta su resultado y revisa el historial de ejecuciones.  Link expone un conjunto de endpoints genéricos: el servicio a ejecutar se elige en la ruta con {service}/{subservice}. El cuerpo de la petición y la forma de la respuesta dependen del servicio elegido; cada servicio define sus propios campos. Consulta el catálogo de servicios para el detalle de cada uno. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://link.kiban.com y sandbox en https://sandbox.link.kiban.com. En sandbox la ejecución no llama al proveedor real: devuelve un test case configurable, para que puedas integrar el contrato del servicio sin costo ni credenciales reales.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package kiban.sdk.link.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import kiban.sdk.link.model.ControllerMicroserviceModelMicroserviceResumeDto;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ControllerMicroserviceModelLinkExecutionPage
 */
public class ControllerMicroserviceModelLinkExecutionPageTest {
    private final ControllerMicroserviceModelLinkExecutionPage model = new ControllerMicroserviceModelLinkExecutionPage();

    /**
     * Model tests for ControllerMicroserviceModelLinkExecutionPage
     */
    @Test
    public void testControllerMicroserviceModelLinkExecutionPage() {
        // TODO: test ControllerMicroserviceModelLinkExecutionPage
    }

    /**
     * Test the property 'currentPage'
     */
    @Test
    public void currentPageTest() {
        // TODO: test currentPage
    }

    /**
     * Test the property 'hasNextPage'
     */
    @Test
    public void hasNextPageTest() {
        // TODO: test hasNextPage
    }

    /**
     * Test the property 'items'
     */
    @Test
    public void itemsTest() {
        // TODO: test items
    }

}
