// <auto-generated>
/*
 * Workfloo API
 *
 * API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hola@kiban.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Kiban.Workfloo.Client;

namespace Kiban.Workfloo.Model
{
    /// <summary>
    /// ControllerWorkflooModelData
    /// </summary>
    public partial class ControllerWorkflooModelData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ControllerWorkflooModelData" /> class.
        /// </summary>
        /// <param name="fields">fields</param>
        /// <param name="section">section</param>
        [JsonConstructor]
        public ControllerWorkflooModelData(Option<List<Dictionary<string, Object>>?> fields = default, Option<Dictionary<string, string>?> section = default)
        {
            FieldsOption = fields;
            SectionOption = section;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Fields
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Dictionary<string, Object>>?> FieldsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Fields
        /// </summary>
        [JsonPropertyName("fields")]
        public List<Dictionary<string, Object>>? Fields { get { return this.FieldsOption.Value; } set { this.FieldsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Section
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, string>?> SectionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Section
        /// </summary>
        [JsonPropertyName("section")]
        public Dictionary<string, string>? Section { get { return this.SectionOption.Value; } set { this.SectionOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ControllerWorkflooModelData {\n");
            sb.Append("  Fields: ").Append(Fields).Append("\n");
            sb.Append("  Section: ").Append(Section).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ControllerWorkflooModelData" />
    /// </summary>
    public partial class ControllerWorkflooModelDataJsonConverter : JsonConverter<ControllerWorkflooModelData>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ControllerWorkflooModelDataJsonConverter" /> class.
        /// </summary>
        public ControllerWorkflooModelDataJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ControllerWorkflooModelData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ControllerWorkflooModelData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<Dictionary<string, Object>>?> fields = default;
            Option<Dictionary<string, string>?> section = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "fields":
                            fields = new Option<List<Dictionary<string, Object>>?>(JsonSerializer.Deserialize<List<Dictionary<string, Object>>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "section":
                            section = new Option<Dictionary<string, string>?>(JsonSerializer.Deserialize<Dictionary<string, string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            return new ControllerWorkflooModelData(fields, section);
        }

        /// <summary>
        /// Serializes a <see cref="ControllerWorkflooModelData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="controllerWorkflooModelData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ControllerWorkflooModelData controllerWorkflooModelData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, controllerWorkflooModelData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ControllerWorkflooModelData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="controllerWorkflooModelData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ControllerWorkflooModelData controllerWorkflooModelData, JsonSerializerOptions jsonSerializerOptions)
        {
            if (controllerWorkflooModelData.FieldsOption.IsSet)
                if (controllerWorkflooModelData.FieldsOption.Value != null)
                {
                    writer.WritePropertyName("fields");
                    JsonSerializer.Serialize(writer, controllerWorkflooModelData.Fields, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("fields");
            if (controllerWorkflooModelData.SectionOption.IsSet)
                if (controllerWorkflooModelData.SectionOption.Value != null)
                {
                    writer.WritePropertyName("section");
                    JsonSerializer.Serialize(writer, controllerWorkflooModelData.Section, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("section");
        }
    }
}
