/*
 * Link API
 * API pública de Link (Kiban): ejecuta un servicio de consulta/validación del catálogo Link (curp, sat, imss, nip, sms, buró de crédito, etc.), consulta su resultado y revisa el historial de ejecuciones.  Link expone un conjunto de endpoints genéricos: el servicio a ejecutar se elige en la ruta con {service}/{subservice}. El cuerpo de la petición y la forma de la respuesta dependen del servicio elegido; cada servicio define sus propios campos. Consulta el catálogo de servicios para el detalle de cada uno. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://link.kiban.com y sandbox en https://sandbox.link.kiban.com. En sandbox la ejecución no llama al proveedor real: devuelve un test case configurable, para que puedas integrar el contrato del servicio sin costo ni credenciales reales.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package kiban.sdk.link.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import kiban.sdk.link.JSON;

/**
 * ControllerMicroserviceModelApiDataFileDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-14T10:54:41.723092-06:00[America/Mexico_City]", comments = "Generator version: 7.24.0")
public class ControllerMicroserviceModelApiDataFileDto {
  public static final String SERIALIZED_NAME_CONTENT = "content";
  @SerializedName(SERIALIZED_NAME_CONTENT)
  @javax.annotation.Nullable
  private List<Integer> content = new ArrayList<>();

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_PATH = "path";
  @SerializedName(SERIALIZED_NAME_PATH)
  @javax.annotation.Nullable
  private String path;

  public ControllerMicroserviceModelApiDataFileDto() {
  }

  public ControllerMicroserviceModelApiDataFileDto content(@javax.annotation.Nullable List<Integer> content) {
    this.content = content;
    return this;
  }

  public ControllerMicroserviceModelApiDataFileDto addContentItem(Integer contentItem) {
    if (this.content == null) {
      this.content = new ArrayList<>();
    }
    this.content.add(contentItem);
    return this;
  }

  /**
   * Get content
   * @return content
   */
  @javax.annotation.Nullable
  public List<Integer> getContent() {
    return content;
  }

  public void setContent(@javax.annotation.Nullable List<Integer> content) {
    this.content = content;
  }


  public ControllerMicroserviceModelApiDataFileDto name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public ControllerMicroserviceModelApiDataFileDto path(@javax.annotation.Nullable String path) {
    this.path = path;
    return this;
  }

  /**
   * Get path
   * @return path
   */
  @javax.annotation.Nullable
  public String getPath() {
    return path;
  }

  public void setPath(@javax.annotation.Nullable String path) {
    this.path = path;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ControllerMicroserviceModelApiDataFileDto controllerMicroserviceModelApiDataFileDto = (ControllerMicroserviceModelApiDataFileDto) o;
    return Objects.equals(this.content, controllerMicroserviceModelApiDataFileDto.content) &&
        Objects.equals(this.name, controllerMicroserviceModelApiDataFileDto.name) &&
        Objects.equals(this.path, controllerMicroserviceModelApiDataFileDto.path);
  }

  @Override
  public int hashCode() {
    return Objects.hash(content, name, path);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ControllerMicroserviceModelApiDataFileDto {\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("content", "name", "path"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ControllerMicroserviceModelApiDataFileDto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ControllerMicroserviceModelApiDataFileDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ControllerMicroserviceModelApiDataFileDto is not found in the empty JSON string", ControllerMicroserviceModelApiDataFileDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ControllerMicroserviceModelApiDataFileDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ControllerMicroserviceModelApiDataFileDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("content") != null && !jsonObj.get("content").isJsonNull() && !jsonObj.get("content").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `content` to be an array in the JSON string but got `%s`", jsonObj.get("content").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("path") != null && !jsonObj.get("path").isJsonNull()) && !jsonObj.get("path").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `path` to be a primitive type in the JSON string but got `%s`", jsonObj.get("path").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ControllerMicroserviceModelApiDataFileDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ControllerMicroserviceModelApiDataFileDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ControllerMicroserviceModelApiDataFileDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ControllerMicroserviceModelApiDataFileDto.class));

       return (TypeAdapter<T>) new TypeAdapter<ControllerMicroserviceModelApiDataFileDto>() {
           @Override
           public void write(JsonWriter out, ControllerMicroserviceModelApiDataFileDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ControllerMicroserviceModelApiDataFileDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ControllerMicroserviceModelApiDataFileDto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ControllerMicroserviceModelApiDataFileDto
   * @throws IOException if the JSON string is invalid with respect to ControllerMicroserviceModelApiDataFileDto
   */
  public static ControllerMicroserviceModelApiDataFileDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ControllerMicroserviceModelApiDataFileDto.class);
  }

  /**
   * Convert an instance of ControllerMicroserviceModelApiDataFileDto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

