/*
 * Workfloo API
 *
 * API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kiban.sdk.workfloo.Model;
using kiban.sdk.workfloo.Client;
using System.Reflection;

namespace kiban.sdk.workfloo.Test.Model
{
    /// <summary>
    ///  Class for testing ControllerWorkflooModelLinkNipStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ControllerWorkflooModelLinkNipStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ControllerWorkflooModelLinkNipStatus
        //private ControllerWorkflooModelLinkNipStatus instance;

        public ControllerWorkflooModelLinkNipStatusTests()
        {
            // TODO uncomment below to create an instance of ControllerWorkflooModelLinkNipStatus
            //instance = new ControllerWorkflooModelLinkNipStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ControllerWorkflooModelLinkNipStatus
        /// </summary>
        [Fact]
        public void ControllerWorkflooModelLinkNipStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" ControllerWorkflooModelLinkNipStatus
            //Assert.IsType<ControllerWorkflooModelLinkNipStatus>(instance);
        }

        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Fact]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }

        /// <summary>
        /// Test the property 'CountryCode'
        /// </summary>
        [Fact]
        public void CountryCodeTest()
        {
            // TODO unit test for the property 'CountryCode'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Events'
        /// </summary>
        [Fact]
        public void EventsTest()
        {
            // TODO unit test for the property 'Events'
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }

        /// <summary>
        /// Test the property 'KeyTypeNode'
        /// </summary>
        [Fact]
        public void KeyTypeNodeTest()
        {
            // TODO unit test for the property 'KeyTypeNode'
        }

        /// <summary>
        /// Test the property 'NipType'
        /// </summary>
        [Fact]
        public void NipTypeTest()
        {
            // TODO unit test for the property 'NipType'
        }

        /// <summary>
        /// Test the property 'Phase'
        /// </summary>
        [Fact]
        public void PhaseTest()
        {
            // TODO unit test for the property 'Phase'
        }

        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Fact]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }

        /// <summary>
        /// Test the property 'PrivacyNotice'
        /// </summary>
        [Fact]
        public void PrivacyNoticeTest()
        {
            // TODO unit test for the property 'PrivacyNotice'
        }

        /// <summary>
        /// Test the property 'Terms'
        /// </summary>
        [Fact]
        public void TermsTest()
        {
            // TODO unit test for the property 'Terms'
        }

        /// <summary>
        /// Test the property 'Widget'
        /// </summary>
        [Fact]
        public void WidgetTest()
        {
            // TODO unit test for the property 'Widget'
        }
    }
}
