/*
 * Workfloo API
 *
 * API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kiban.sdk.workfloo.Model;
using kiban.sdk.workfloo.Client;
using System.Reflection;

namespace kiban.sdk.workfloo.Test.Model
{
    /// <summary>
    ///  Class for testing ControllerWorkflooModelApiDataResume
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ControllerWorkflooModelApiDataResumeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ControllerWorkflooModelApiDataResume
        //private ControllerWorkflooModelApiDataResume instance;

        public ControllerWorkflooModelApiDataResumeTests()
        {
            // TODO uncomment below to create an instance of ControllerWorkflooModelApiDataResume
            //instance = new ControllerWorkflooModelApiDataResume();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ControllerWorkflooModelApiDataResume
        /// </summary>
        [Fact]
        public void ControllerWorkflooModelApiDataResumeInstanceTest()
        {
            // TODO uncomment below to test "IsType" ControllerWorkflooModelApiDataResume
            //Assert.IsType<ControllerWorkflooModelApiDataResume>(instance);
        }

        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Fact]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }

        /// <summary>
        /// Test the property 'Headers'
        /// </summary>
        [Fact]
        public void HeadersTest()
        {
            // TODO unit test for the property 'Headers'
        }

        /// <summary>
        /// Test the property 'HttpCode'
        /// </summary>
        [Fact]
        public void HttpCodeTest()
        {
            // TODO unit test for the property 'HttpCode'
        }

        /// <summary>
        /// Test the property 'QueryParams'
        /// </summary>
        [Fact]
        public void QueryParamsTest()
        {
            // TODO unit test for the property 'QueryParams'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
    }
}
