/*
 * Workfloo API
 *
 * API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kiban.sdk.workfloo.Model;
using kiban.sdk.workfloo.Client;
using System.Reflection;

namespace kiban.sdk.workfloo.Test.Model
{
    /// <summary>
    ///  Class for testing ControllerWorkflooModelDecisionTree
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ControllerWorkflooModelDecisionTreeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ControllerWorkflooModelDecisionTree
        //private ControllerWorkflooModelDecisionTree instance;

        public ControllerWorkflooModelDecisionTreeTests()
        {
            // TODO uncomment below to create an instance of ControllerWorkflooModelDecisionTree
            //instance = new ControllerWorkflooModelDecisionTree();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ControllerWorkflooModelDecisionTree
        /// </summary>
        [Fact]
        public void ControllerWorkflooModelDecisionTreeInstanceTest()
        {
            // TODO uncomment below to test "IsType" ControllerWorkflooModelDecisionTree
            //Assert.IsType<ControllerWorkflooModelDecisionTree>(instance);
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'NameNode'
        /// </summary>
        [Fact]
        public void NameNodeTest()
        {
            // TODO unit test for the property 'NameNode'
        }

        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Fact]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }
    }
}
