/*
 * Workfloo API
 *
 * API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kiban.sdk.workfloo.Model;
using kiban.sdk.workfloo.Client;
using System.Reflection;

namespace kiban.sdk.workfloo.Test.Model
{
    /// <summary>
    ///  Class for testing ControllerWorkflooDefinitionModelField
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ControllerWorkflooDefinitionModelFieldTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ControllerWorkflooDefinitionModelField
        //private ControllerWorkflooDefinitionModelField instance;

        public ControllerWorkflooDefinitionModelFieldTests()
        {
            // TODO uncomment below to create an instance of ControllerWorkflooDefinitionModelField
            //instance = new ControllerWorkflooDefinitionModelField();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ControllerWorkflooDefinitionModelField
        /// </summary>
        [Fact]
        public void ControllerWorkflooDefinitionModelFieldInstanceTest()
        {
            // TODO uncomment below to test "IsType" ControllerWorkflooDefinitionModelField
            //Assert.IsType<ControllerWorkflooDefinitionModelField>(instance);
        }

        /// <summary>
        /// Test the property 'FieldMetadata'
        /// </summary>
        [Fact]
        public void FieldMetadataTest()
        {
            // TODO unit test for the property 'FieldMetadata'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Predefined'
        /// </summary>
        [Fact]
        public void PredefinedTest()
        {
            // TODO unit test for the property 'Predefined'
        }

        /// <summary>
        /// Test the property 'Required'
        /// </summary>
        [Fact]
        public void RequiredTest()
        {
            // TODO unit test for the property 'Required'
        }

        /// <summary>
        /// Test the property 'Section'
        /// </summary>
        [Fact]
        public void SectionTest()
        {
            // TODO unit test for the property 'Section'
        }

        /// <summary>
        /// Test the property 'Set'
        /// </summary>
        [Fact]
        public void SetTest()
        {
            // TODO unit test for the property 'Set'
        }

        /// <summary>
        /// Test the property 'ShowIf'
        /// </summary>
        [Fact]
        public void ShowIfTest()
        {
            // TODO unit test for the property 'ShowIf'
        }
    }
}
