/*
 * Workfloo API
 *
 * API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kiban.sdk.workfloo.Model;
using kiban.sdk.workfloo.Client;
using System.Reflection;

namespace kiban.sdk.workfloo.Test.Model
{
    /// <summary>
    ///  Class for testing ControllerWorkflooModelWorkflooResume
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ControllerWorkflooModelWorkflooResumeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ControllerWorkflooModelWorkflooResume
        //private ControllerWorkflooModelWorkflooResume instance;

        public ControllerWorkflooModelWorkflooResumeTests()
        {
            // TODO uncomment below to create an instance of ControllerWorkflooModelWorkflooResume
            //instance = new ControllerWorkflooModelWorkflooResume();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ControllerWorkflooModelWorkflooResume
        /// </summary>
        [Fact]
        public void ControllerWorkflooModelWorkflooResumeInstanceTest()
        {
            // TODO uncomment below to test "IsType" ControllerWorkflooModelWorkflooResume
            //Assert.IsType<ControllerWorkflooModelWorkflooResume>(instance);
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'IdUnykoo'
        /// </summary>
        [Fact]
        public void IdUnykooTest()
        {
            // TODO unit test for the property 'IdUnykoo'
        }

        /// <summary>
        /// Test the property 'IpOrigin'
        /// </summary>
        [Fact]
        public void IpOriginTest()
        {
            // TODO unit test for the property 'IpOrigin'
        }

        /// <summary>
        /// Test the property 'Labels'
        /// </summary>
        [Fact]
        public void LabelsTest()
        {
            // TODO unit test for the property 'Labels'
        }

        /// <summary>
        /// Test the property 'Modified'
        /// </summary>
        [Fact]
        public void ModifiedTest()
        {
            // TODO unit test for the property 'Modified'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Nodes'
        /// </summary>
        [Fact]
        public void NodesTest()
        {
            // TODO unit test for the property 'Nodes'
        }

        /// <summary>
        /// Test the property 'Origin'
        /// </summary>
        [Fact]
        public void OriginTest()
        {
            // TODO unit test for the property 'Origin'
        }

        /// <summary>
        /// Test the property 'SceneryId'
        /// </summary>
        [Fact]
        public void SceneryIdTest()
        {
            // TODO unit test for the property 'SceneryId'
        }

        /// <summary>
        /// Test the property 'SceneryName'
        /// </summary>
        [Fact]
        public void SceneryNameTest()
        {
            // TODO unit test for the property 'SceneryName'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
    }
}
