/*
 * Workfloo API
 *
 * API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kiban.sdk.workfloo.Model;
using kiban.sdk.workfloo.Client;
using System.Reflection;

namespace kiban.sdk.workfloo.Test.Model
{
    /// <summary>
    ///  Class for testing ControllerWorkflooDefinitionModelFieldMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ControllerWorkflooDefinitionModelFieldMetadataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ControllerWorkflooDefinitionModelFieldMetadata
        //private ControllerWorkflooDefinitionModelFieldMetadata instance;

        public ControllerWorkflooDefinitionModelFieldMetadataTests()
        {
            // TODO uncomment below to create an instance of ControllerWorkflooDefinitionModelFieldMetadata
            //instance = new ControllerWorkflooDefinitionModelFieldMetadata();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ControllerWorkflooDefinitionModelFieldMetadata
        /// </summary>
        [Fact]
        public void ControllerWorkflooDefinitionModelFieldMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsType" ControllerWorkflooDefinitionModelFieldMetadata
            //Assert.IsType<ControllerWorkflooDefinitionModelFieldMetadata>(instance);
        }

        /// <summary>
        /// Test the property 'AutoFilledBy'
        /// </summary>
        [Fact]
        public void AutoFilledByTest()
        {
            // TODO unit test for the property 'AutoFilledBy'
        }

        /// <summary>
        /// Test the property 'AutofillNodeId'
        /// </summary>
        [Fact]
        public void AutofillNodeIdTest()
        {
            // TODO unit test for the property 'AutofillNodeId'
        }

        /// <summary>
        /// Test the property 'DefaultValue'
        /// </summary>
        [Fact]
        public void DefaultValueTest()
        {
            // TODO unit test for the property 'DefaultValue'
        }

        /// <summary>
        /// Test the property 'Html'
        /// </summary>
        [Fact]
        public void HtmlTest()
        {
            // TODO unit test for the property 'Html'
        }

        /// <summary>
        /// Test the property 'Map'
        /// </summary>
        [Fact]
        public void MapTest()
        {
            // TODO unit test for the property 'Map'
        }

        /// <summary>
        /// Test the property 'Max'
        /// </summary>
        [Fact]
        public void MaxTest()
        {
            // TODO unit test for the property 'Max'
        }

        /// <summary>
        /// Test the property 'MaxLength'
        /// </summary>
        [Fact]
        public void MaxLengthTest()
        {
            // TODO unit test for the property 'MaxLength'
        }

        /// <summary>
        /// Test the property 'MaxVal'
        /// </summary>
        [Fact]
        public void MaxValTest()
        {
            // TODO unit test for the property 'MaxVal'
        }

        /// <summary>
        /// Test the property 'Min'
        /// </summary>
        [Fact]
        public void MinTest()
        {
            // TODO unit test for the property 'Min'
        }

        /// <summary>
        /// Test the property 'MinLength'
        /// </summary>
        [Fact]
        public void MinLengthTest()
        {
            // TODO unit test for the property 'MinLength'
        }

        /// <summary>
        /// Test the property 'MinVal'
        /// </summary>
        [Fact]
        public void MinValTest()
        {
            // TODO unit test for the property 'MinVal'
        }

        /// <summary>
        /// Test the property 'Regex'
        /// </summary>
        [Fact]
        public void RegexTest()
        {
            // TODO unit test for the property 'Regex'
        }

        /// <summary>
        /// Test the property 'RegexMessage'
        /// </summary>
        [Fact]
        public void RegexMessageTest()
        {
            // TODO unit test for the property 'RegexMessage'
        }

        /// <summary>
        /// Test the property 'Show'
        /// </summary>
        [Fact]
        public void ShowTest()
        {
            // TODO unit test for the property 'Show'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
    }
}
