/*
 * Workfloo API
 *
 * API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kiban.sdk.workfloo.Model;
using kiban.sdk.workfloo.Client;
using System.Reflection;

namespace kiban.sdk.workfloo.Test.Model
{
    /// <summary>
    ///  Class for testing ControllerWorkflooModelNode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ControllerWorkflooModelNodeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ControllerWorkflooModelNode
        //private ControllerWorkflooModelNode instance;

        public ControllerWorkflooModelNodeTests()
        {
            // TODO uncomment below to create an instance of ControllerWorkflooModelNode
            //instance = new ControllerWorkflooModelNode();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ControllerWorkflooModelNode
        /// </summary>
        [Fact]
        public void ControllerWorkflooModelNodeInstanceTest()
        {
            // TODO uncomment below to test "IsType" ControllerWorkflooModelNode
            //Assert.IsType<ControllerWorkflooModelNode>(instance);
        }

        /// <summary>
        /// Test the property 'Api'
        /// </summary>
        [Fact]
        public void ApiTest()
        {
            // TODO unit test for the property 'Api'
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }

        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Fact]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }

        /// <summary>
        /// Test the property 'DecisionTree'
        /// </summary>
        [Fact]
        public void DecisionTreeTest()
        {
            // TODO unit test for the property 'DecisionTree'
        }

        /// <summary>
        /// Test the property 'Form'
        /// </summary>
        [Fact]
        public void FormTest()
        {
            // TODO unit test for the property 'Form'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Link'
        /// </summary>
        [Fact]
        public void LinkTest()
        {
            // TODO unit test for the property 'Link'
        }

        /// <summary>
        /// Test the property 'Modified'
        /// </summary>
        [Fact]
        public void ModifiedTest()
        {
            // TODO unit test for the property 'Modified'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Ruleset'
        /// </summary>
        [Fact]
        public void RulesetTest()
        {
            // TODO unit test for the property 'Ruleset'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Variables'
        /// </summary>
        [Fact]
        public void VariablesTest()
        {
            // TODO unit test for the property 'Variables'
        }
    }
}
