// <auto-generated>
/*
 * Workfloo API
 *
 * API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using kiban.sdk.workfloo.Client;

namespace kiban.sdk.workfloo.Model
{
    /// <summary>
    /// ControllerWorkflooDefinitionModelSetData
    /// </summary>
    public partial class ControllerWorkflooDefinitionModelSetData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ControllerWorkflooDefinitionModelSetData" /> class.
        /// </summary>
        /// <param name="fields">fields</param>
        /// <param name="optionalAt">optionalAt</param>
        /// <param name="required">required</param>
        [JsonConstructor]
        public ControllerWorkflooDefinitionModelSetData(Option<List<ControllerWorkflooDefinitionModelField>?> fields = default, Option<List<string>?> optionalAt = default, Option<List<string>?> required = default)
        {
            FieldsOption = fields;
            OptionalAtOption = optionalAt;
            RequiredOption = required;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Fields
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<ControllerWorkflooDefinitionModelField>?> FieldsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Fields
        /// </summary>
        [JsonPropertyName("fields")]
        public List<ControllerWorkflooDefinitionModelField>? Fields { get { return this.FieldsOption.Value; } set { this.FieldsOption = new(value); } }

        /// <summary>
        /// Used to track the state of OptionalAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> OptionalAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets OptionalAt
        /// </summary>
        [JsonPropertyName("optionalAt")]
        public List<string>? OptionalAt { get { return this.OptionalAtOption.Value; } set { this.OptionalAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of Required
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> RequiredOption { get; private set; }

        /// <summary>
        /// Gets or Sets Required
        /// </summary>
        [JsonPropertyName("required")]
        public List<string>? Required { get { return this.RequiredOption.Value; } set { this.RequiredOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ControllerWorkflooDefinitionModelSetData {\n");
            sb.Append("  Fields: ").Append(Fields).Append("\n");
            sb.Append("  OptionalAt: ").Append(OptionalAt).Append("\n");
            sb.Append("  Required: ").Append(Required).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ControllerWorkflooDefinitionModelSetData" />
    /// </summary>
    public partial class ControllerWorkflooDefinitionModelSetDataJsonConverter : JsonConverter<ControllerWorkflooDefinitionModelSetData>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ControllerWorkflooDefinitionModelSetDataJsonConverter" /> class.
        /// </summary>
        public ControllerWorkflooDefinitionModelSetDataJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ControllerWorkflooDefinitionModelSetData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ControllerWorkflooDefinitionModelSetData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<ControllerWorkflooDefinitionModelField>?> fields = default;
            Option<List<string>?> optionalAt = default;
            Option<List<string>?> required = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "fields":
                            fields = new Option<List<ControllerWorkflooDefinitionModelField>?>(JsonSerializer.Deserialize<List<ControllerWorkflooDefinitionModelField>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "optionalAt":
                            optionalAt = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "required":
                            required = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (fields.IsSet && fields.Value == null)
                throw new ArgumentNullException(nameof(fields), "Property is not nullable for class ControllerWorkflooDefinitionModelSetData.");

            if (optionalAt.IsSet && optionalAt.Value == null)
                throw new ArgumentNullException(nameof(optionalAt), "Property is not nullable for class ControllerWorkflooDefinitionModelSetData.");

            if (required.IsSet && required.Value == null)
                throw new ArgumentNullException(nameof(required), "Property is not nullable for class ControllerWorkflooDefinitionModelSetData.");

            return new ControllerWorkflooDefinitionModelSetData(fields, optionalAt, required);
        }

        /// <summary>
        /// Serializes a <see cref="ControllerWorkflooDefinitionModelSetData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="controllerWorkflooDefinitionModelSetData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ControllerWorkflooDefinitionModelSetData controllerWorkflooDefinitionModelSetData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, controllerWorkflooDefinitionModelSetData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ControllerWorkflooDefinitionModelSetData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="controllerWorkflooDefinitionModelSetData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ControllerWorkflooDefinitionModelSetData controllerWorkflooDefinitionModelSetData, JsonSerializerOptions jsonSerializerOptions)
        {
            if (controllerWorkflooDefinitionModelSetData.FieldsOption.IsSet && controllerWorkflooDefinitionModelSetData.Fields == null)
                throw new ArgumentNullException(nameof(controllerWorkflooDefinitionModelSetData.Fields), "Property is required for class ControllerWorkflooDefinitionModelSetData.");

            if (controllerWorkflooDefinitionModelSetData.OptionalAtOption.IsSet && controllerWorkflooDefinitionModelSetData.OptionalAt == null)
                throw new ArgumentNullException(nameof(controllerWorkflooDefinitionModelSetData.OptionalAt), "Property is required for class ControllerWorkflooDefinitionModelSetData.");

            if (controllerWorkflooDefinitionModelSetData.RequiredOption.IsSet && controllerWorkflooDefinitionModelSetData.Required == null)
                throw new ArgumentNullException(nameof(controllerWorkflooDefinitionModelSetData.Required), "Property is required for class ControllerWorkflooDefinitionModelSetData.");

            if (controllerWorkflooDefinitionModelSetData.FieldsOption.IsSet)
            {
                writer.WritePropertyName("fields");
                JsonSerializer.Serialize(writer, controllerWorkflooDefinitionModelSetData.Fields, jsonSerializerOptions);
            }
            if (controllerWorkflooDefinitionModelSetData.OptionalAtOption.IsSet)
            {
                writer.WritePropertyName("optionalAt");
                JsonSerializer.Serialize(writer, controllerWorkflooDefinitionModelSetData.OptionalAt, jsonSerializerOptions);
            }
            if (controllerWorkflooDefinitionModelSetData.RequiredOption.IsSet)
            {
                writer.WritePropertyName("required");
                JsonSerializer.Serialize(writer, controllerWorkflooDefinitionModelSetData.Required, jsonSerializerOptions);
            }
        }
    }
}
