// <auto-generated>
/*
 * Workfloo API
 *
 * API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using kiban.sdk.workfloo.Client;

namespace kiban.sdk.workfloo.Model
{
    /// <summary>
    /// ControllerWorkflooModelValidationStatus
    /// </summary>
    public partial class ControllerWorkflooModelValidationStatus : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ControllerWorkflooModelValidationStatus" /> class.
        /// </summary>
        /// <param name="fields">fields</param>
        /// <param name="instruction">instruction</param>
        /// <param name="reviewerNote">reviewerNote</param>
        [JsonConstructor]
        public ControllerWorkflooModelValidationStatus(Option<List<ControllerWorkflooModelValidationField>?> fields = default, Option<string?> instruction = default, Option<string?> reviewerNote = default)
        {
            FieldsOption = fields;
            InstructionOption = instruction;
            ReviewerNoteOption = reviewerNote;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Fields
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<ControllerWorkflooModelValidationField>?> FieldsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Fields
        /// </summary>
        [JsonPropertyName("fields")]
        public List<ControllerWorkflooModelValidationField>? Fields { get { return this.FieldsOption.Value; } set { this.FieldsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Instruction
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> InstructionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Instruction
        /// </summary>
        [JsonPropertyName("instruction")]
        public string? Instruction { get { return this.InstructionOption.Value; } set { this.InstructionOption = new(value); } }

        /// <summary>
        /// Used to track the state of ReviewerNote
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ReviewerNoteOption { get; private set; }

        /// <summary>
        /// Gets or Sets ReviewerNote
        /// </summary>
        [JsonPropertyName("reviewerNote")]
        public string? ReviewerNote { get { return this.ReviewerNoteOption.Value; } set { this.ReviewerNoteOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ControllerWorkflooModelValidationStatus {\n");
            sb.Append("  Fields: ").Append(Fields).Append("\n");
            sb.Append("  Instruction: ").Append(Instruction).Append("\n");
            sb.Append("  ReviewerNote: ").Append(ReviewerNote).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ControllerWorkflooModelValidationStatus" />
    /// </summary>
    public partial class ControllerWorkflooModelValidationStatusJsonConverter : JsonConverter<ControllerWorkflooModelValidationStatus>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ControllerWorkflooModelValidationStatusJsonConverter" /> class.
        /// </summary>
        public ControllerWorkflooModelValidationStatusJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ControllerWorkflooModelValidationStatus" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ControllerWorkflooModelValidationStatus Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<ControllerWorkflooModelValidationField>?> fields = default;
            Option<string?> instruction = default;
            Option<string?> reviewerNote = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "fields":
                            fields = new Option<List<ControllerWorkflooModelValidationField>?>(JsonSerializer.Deserialize<List<ControllerWorkflooModelValidationField>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "instruction":
                            instruction = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "reviewerNote":
                            reviewerNote = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (fields.IsSet && fields.Value == null)
                throw new ArgumentNullException(nameof(fields), "Property is not nullable for class ControllerWorkflooModelValidationStatus.");

            if (instruction.IsSet && instruction.Value == null)
                throw new ArgumentNullException(nameof(instruction), "Property is not nullable for class ControllerWorkflooModelValidationStatus.");

            if (reviewerNote.IsSet && reviewerNote.Value == null)
                throw new ArgumentNullException(nameof(reviewerNote), "Property is not nullable for class ControllerWorkflooModelValidationStatus.");

            return new ControllerWorkflooModelValidationStatus(fields, instruction, reviewerNote);
        }

        /// <summary>
        /// Serializes a <see cref="ControllerWorkflooModelValidationStatus" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="controllerWorkflooModelValidationStatus"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ControllerWorkflooModelValidationStatus controllerWorkflooModelValidationStatus, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, controllerWorkflooModelValidationStatus, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ControllerWorkflooModelValidationStatus" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="controllerWorkflooModelValidationStatus"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ControllerWorkflooModelValidationStatus controllerWorkflooModelValidationStatus, JsonSerializerOptions jsonSerializerOptions)
        {
            if (controllerWorkflooModelValidationStatus.FieldsOption.IsSet && controllerWorkflooModelValidationStatus.Fields == null)
                throw new ArgumentNullException(nameof(controllerWorkflooModelValidationStatus.Fields), "Property is required for class ControllerWorkflooModelValidationStatus.");

            if (controllerWorkflooModelValidationStatus.InstructionOption.IsSet && controllerWorkflooModelValidationStatus.Instruction == null)
                throw new ArgumentNullException(nameof(controllerWorkflooModelValidationStatus.Instruction), "Property is required for class ControllerWorkflooModelValidationStatus.");

            if (controllerWorkflooModelValidationStatus.ReviewerNoteOption.IsSet && controllerWorkflooModelValidationStatus.ReviewerNote == null)
                throw new ArgumentNullException(nameof(controllerWorkflooModelValidationStatus.ReviewerNote), "Property is required for class ControllerWorkflooModelValidationStatus.");

            if (controllerWorkflooModelValidationStatus.FieldsOption.IsSet)
            {
                writer.WritePropertyName("fields");
                JsonSerializer.Serialize(writer, controllerWorkflooModelValidationStatus.Fields, jsonSerializerOptions);
            }
            if (controllerWorkflooModelValidationStatus.InstructionOption.IsSet)
                writer.WriteString("instruction", controllerWorkflooModelValidationStatus.Instruction);

            if (controllerWorkflooModelValidationStatus.ReviewerNoteOption.IsSet)
                writer.WriteString("reviewerNote", controllerWorkflooModelValidationStatus.ReviewerNote);
        }
    }
}
