// <auto-generated>
/*
 * Workfloo API
 *
 * API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using kiban.sdk.workfloo.Client;

namespace kiban.sdk.workfloo.Model
{
    /// <summary>
    /// ControllerWorkflooModelRuleset
    /// </summary>
    public partial class ControllerWorkflooModelRuleset : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ControllerWorkflooModelRuleset" /> class.
        /// </summary>
        /// <param name="decision">decision</param>
        /// <param name="exit">exit</param>
        /// <param name="labels">labels</param>
        [JsonConstructor]
        public ControllerWorkflooModelRuleset(Option<List<ControllerWorkflooModelRules>?> decision = default, Option<string?> exit = default, Option<List<string>?> labels = default)
        {
            DecisionOption = decision;
            ExitOption = exit;
            LabelsOption = labels;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Decision
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<ControllerWorkflooModelRules>?> DecisionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Decision
        /// </summary>
        [JsonPropertyName("decision")]
        public List<ControllerWorkflooModelRules>? Decision { get { return this.DecisionOption.Value; } set { this.DecisionOption = new(value); } }

        /// <summary>
        /// Used to track the state of Exit
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ExitOption { get; private set; }

        /// <summary>
        /// Gets or Sets Exit
        /// </summary>
        [JsonPropertyName("exit")]
        public string? Exit { get { return this.ExitOption.Value; } set { this.ExitOption = new(value); } }

        /// <summary>
        /// Used to track the state of Labels
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> LabelsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Labels
        /// </summary>
        [JsonPropertyName("labels")]
        public List<string>? Labels { get { return this.LabelsOption.Value; } set { this.LabelsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ControllerWorkflooModelRuleset {\n");
            sb.Append("  Decision: ").Append(Decision).Append("\n");
            sb.Append("  Exit: ").Append(Exit).Append("\n");
            sb.Append("  Labels: ").Append(Labels).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ControllerWorkflooModelRuleset" />
    /// </summary>
    public partial class ControllerWorkflooModelRulesetJsonConverter : JsonConverter<ControllerWorkflooModelRuleset>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ControllerWorkflooModelRulesetJsonConverter" /> class.
        /// </summary>
        public ControllerWorkflooModelRulesetJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ControllerWorkflooModelRuleset" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ControllerWorkflooModelRuleset Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<ControllerWorkflooModelRules>?> decision = default;
            Option<string?> exit = default;
            Option<List<string>?> labels = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "decision":
                            decision = new Option<List<ControllerWorkflooModelRules>?>(JsonSerializer.Deserialize<List<ControllerWorkflooModelRules>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "exit":
                            exit = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "labels":
                            labels = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (decision.IsSet && decision.Value == null)
                throw new ArgumentNullException(nameof(decision), "Property is not nullable for class ControllerWorkflooModelRuleset.");

            if (exit.IsSet && exit.Value == null)
                throw new ArgumentNullException(nameof(exit), "Property is not nullable for class ControllerWorkflooModelRuleset.");

            if (labels.IsSet && labels.Value == null)
                throw new ArgumentNullException(nameof(labels), "Property is not nullable for class ControllerWorkflooModelRuleset.");

            return new ControllerWorkflooModelRuleset(decision, exit, labels);
        }

        /// <summary>
        /// Serializes a <see cref="ControllerWorkflooModelRuleset" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="controllerWorkflooModelRuleset"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ControllerWorkflooModelRuleset controllerWorkflooModelRuleset, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, controllerWorkflooModelRuleset, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ControllerWorkflooModelRuleset" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="controllerWorkflooModelRuleset"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ControllerWorkflooModelRuleset controllerWorkflooModelRuleset, JsonSerializerOptions jsonSerializerOptions)
        {
            if (controllerWorkflooModelRuleset.DecisionOption.IsSet && controllerWorkflooModelRuleset.Decision == null)
                throw new ArgumentNullException(nameof(controllerWorkflooModelRuleset.Decision), "Property is required for class ControllerWorkflooModelRuleset.");

            if (controllerWorkflooModelRuleset.ExitOption.IsSet && controllerWorkflooModelRuleset.Exit == null)
                throw new ArgumentNullException(nameof(controllerWorkflooModelRuleset.Exit), "Property is required for class ControllerWorkflooModelRuleset.");

            if (controllerWorkflooModelRuleset.LabelsOption.IsSet && controllerWorkflooModelRuleset.Labels == null)
                throw new ArgumentNullException(nameof(controllerWorkflooModelRuleset.Labels), "Property is required for class ControllerWorkflooModelRuleset.");

            if (controllerWorkflooModelRuleset.DecisionOption.IsSet)
            {
                writer.WritePropertyName("decision");
                JsonSerializer.Serialize(writer, controllerWorkflooModelRuleset.Decision, jsonSerializerOptions);
            }
            if (controllerWorkflooModelRuleset.ExitOption.IsSet)
                writer.WriteString("exit", controllerWorkflooModelRuleset.Exit);

            if (controllerWorkflooModelRuleset.LabelsOption.IsSet)
            {
                writer.WritePropertyName("labels");
                JsonSerializer.Serialize(writer, controllerWorkflooModelRuleset.Labels, jsonSerializerOptions);
            }
        }
    }
}
