// <auto-generated>
/*
 * Workfloo API
 *
 * API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using kiban.sdk.workfloo.Client;

namespace kiban.sdk.workfloo.Model
{
    /// <summary>
    /// ControllerWorkflooModelFormResume
    /// </summary>
    public partial class ControllerWorkflooModelFormResume : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ControllerWorkflooModelFormResume" /> class.
        /// </summary>
        /// <param name="fields">fields</param>
        [JsonConstructor]
        public ControllerWorkflooModelFormResume(Option<Dictionary<string, Object>?> fields = default)
        {
            FieldsOption = fields;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Fields
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, Object>?> FieldsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Fields
        /// </summary>
        [JsonPropertyName("fields")]
        public Dictionary<string, Object>? Fields { get { return this.FieldsOption.Value; } set { this.FieldsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ControllerWorkflooModelFormResume {\n");
            sb.Append("  Fields: ").Append(Fields).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ControllerWorkflooModelFormResume" />
    /// </summary>
    public partial class ControllerWorkflooModelFormResumeJsonConverter : JsonConverter<ControllerWorkflooModelFormResume>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ControllerWorkflooModelFormResumeJsonConverter" /> class.
        /// </summary>
        public ControllerWorkflooModelFormResumeJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ControllerWorkflooModelFormResume" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ControllerWorkflooModelFormResume Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Dictionary<string, Object>?> fields = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "fields":
                            fields = new Option<Dictionary<string, Object>?>(JsonSerializer.Deserialize<Dictionary<string, Object>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (fields.IsSet && fields.Value == null)
                throw new ArgumentNullException(nameof(fields), "Property is not nullable for class ControllerWorkflooModelFormResume.");

            return new ControllerWorkflooModelFormResume(fields);
        }

        /// <summary>
        /// Serializes a <see cref="ControllerWorkflooModelFormResume" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="controllerWorkflooModelFormResume"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ControllerWorkflooModelFormResume controllerWorkflooModelFormResume, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, controllerWorkflooModelFormResume, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ControllerWorkflooModelFormResume" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="controllerWorkflooModelFormResume"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ControllerWorkflooModelFormResume controllerWorkflooModelFormResume, JsonSerializerOptions jsonSerializerOptions)
        {
            if (controllerWorkflooModelFormResume.FieldsOption.IsSet && controllerWorkflooModelFormResume.Fields == null)
                throw new ArgumentNullException(nameof(controllerWorkflooModelFormResume.Fields), "Property is required for class ControllerWorkflooModelFormResume.");

            if (controllerWorkflooModelFormResume.FieldsOption.IsSet)
            {
                writer.WritePropertyName("fields");
                JsonSerializer.Serialize(writer, controllerWorkflooModelFormResume.Fields, jsonSerializerOptions);
            }
        }
    }
}
