// <auto-generated>
/*
 * Workfloo API
 *
 * API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using kiban.sdk.workfloo.Client;

namespace kiban.sdk.workfloo.Model
{
    /// <summary>
    /// ControllerWorkflooModelNipValidateResponse
    /// </summary>
    public partial class ControllerWorkflooModelNipValidateResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ControllerWorkflooModelNipValidateResponse" /> class.
        /// </summary>
        /// <param name="phase">phase</param>
        [JsonConstructor]
        public ControllerWorkflooModelNipValidateResponse(Option<string?> phase = default)
        {
            PhaseOption = phase;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Phase
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PhaseOption { get; private set; }

        /// <summary>
        /// Gets or Sets Phase
        /// </summary>
        [JsonPropertyName("phase")]
        public string? Phase { get { return this.PhaseOption.Value; } set { this.PhaseOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ControllerWorkflooModelNipValidateResponse {\n");
            sb.Append("  Phase: ").Append(Phase).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ControllerWorkflooModelNipValidateResponse" />
    /// </summary>
    public partial class ControllerWorkflooModelNipValidateResponseJsonConverter : JsonConverter<ControllerWorkflooModelNipValidateResponse>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ControllerWorkflooModelNipValidateResponseJsonConverter" /> class.
        /// </summary>
        public ControllerWorkflooModelNipValidateResponseJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ControllerWorkflooModelNipValidateResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ControllerWorkflooModelNipValidateResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> phase = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "phase":
                            phase = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (phase.IsSet && phase.Value == null)
                throw new ArgumentNullException(nameof(phase), "Property is not nullable for class ControllerWorkflooModelNipValidateResponse.");

            return new ControllerWorkflooModelNipValidateResponse(phase);
        }

        /// <summary>
        /// Serializes a <see cref="ControllerWorkflooModelNipValidateResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="controllerWorkflooModelNipValidateResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ControllerWorkflooModelNipValidateResponse controllerWorkflooModelNipValidateResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, controllerWorkflooModelNipValidateResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ControllerWorkflooModelNipValidateResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="controllerWorkflooModelNipValidateResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ControllerWorkflooModelNipValidateResponse controllerWorkflooModelNipValidateResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (controllerWorkflooModelNipValidateResponse.PhaseOption.IsSet && controllerWorkflooModelNipValidateResponse.Phase == null)
                throw new ArgumentNullException(nameof(controllerWorkflooModelNipValidateResponse.Phase), "Property is required for class ControllerWorkflooModelNipValidateResponse.");

            if (controllerWorkflooModelNipValidateResponse.PhaseOption.IsSet)
                writer.WriteString("phase", controllerWorkflooModelNipValidateResponse.Phase);
        }
    }
}
