// <auto-generated>
/*
 * Workfloo API
 *
 * API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using kiban.sdk.workfloo.Client;

namespace kiban.sdk.workfloo.Model
{
    /// <summary>
    /// ControllerWorkflooModelApiData
    /// </summary>
    public partial class ControllerWorkflooModelApiData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ControllerWorkflooModelApiData" /> class.
        /// </summary>
        /// <param name="request">request</param>
        /// <param name="response">response</param>
        [JsonConstructor]
        public ControllerWorkflooModelApiData(Option<ControllerWorkflooModelApiDataResume?> request = default, Option<ControllerWorkflooModelApiDataResume?> response = default)
        {
            RequestOption = request;
            ResponseOption = response;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Request
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ControllerWorkflooModelApiDataResume?> RequestOption { get; private set; }

        /// <summary>
        /// Gets or Sets Request
        /// </summary>
        [JsonPropertyName("request")]
        public ControllerWorkflooModelApiDataResume? Request { get { return this.RequestOption.Value; } set { this.RequestOption = new(value); } }

        /// <summary>
        /// Used to track the state of Response
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ControllerWorkflooModelApiDataResume?> ResponseOption { get; private set; }

        /// <summary>
        /// Gets or Sets Response
        /// </summary>
        [JsonPropertyName("response")]
        public ControllerWorkflooModelApiDataResume? Response { get { return this.ResponseOption.Value; } set { this.ResponseOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ControllerWorkflooModelApiData {\n");
            sb.Append("  Request: ").Append(Request).Append("\n");
            sb.Append("  Response: ").Append(Response).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ControllerWorkflooModelApiData" />
    /// </summary>
    public partial class ControllerWorkflooModelApiDataJsonConverter : JsonConverter<ControllerWorkflooModelApiData>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ControllerWorkflooModelApiDataJsonConverter" /> class.
        /// </summary>
        public ControllerWorkflooModelApiDataJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ControllerWorkflooModelApiData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ControllerWorkflooModelApiData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<ControllerWorkflooModelApiDataResume?> request = default;
            Option<ControllerWorkflooModelApiDataResume?> response = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "request":
                            request = new Option<ControllerWorkflooModelApiDataResume?>(JsonSerializer.Deserialize<ControllerWorkflooModelApiDataResume>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "response":
                            response = new Option<ControllerWorkflooModelApiDataResume?>(JsonSerializer.Deserialize<ControllerWorkflooModelApiDataResume>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (request.IsSet && request.Value == null)
                throw new ArgumentNullException(nameof(request), "Property is not nullable for class ControllerWorkflooModelApiData.");

            if (response.IsSet && response.Value == null)
                throw new ArgumentNullException(nameof(response), "Property is not nullable for class ControllerWorkflooModelApiData.");

            return new ControllerWorkflooModelApiData(request, response);
        }

        /// <summary>
        /// Serializes a <see cref="ControllerWorkflooModelApiData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="controllerWorkflooModelApiData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ControllerWorkflooModelApiData controllerWorkflooModelApiData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, controllerWorkflooModelApiData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ControllerWorkflooModelApiData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="controllerWorkflooModelApiData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ControllerWorkflooModelApiData controllerWorkflooModelApiData, JsonSerializerOptions jsonSerializerOptions)
        {
            if (controllerWorkflooModelApiData.RequestOption.IsSet && controllerWorkflooModelApiData.Request == null)
                throw new ArgumentNullException(nameof(controllerWorkflooModelApiData.Request), "Property is required for class ControllerWorkflooModelApiData.");

            if (controllerWorkflooModelApiData.ResponseOption.IsSet && controllerWorkflooModelApiData.Response == null)
                throw new ArgumentNullException(nameof(controllerWorkflooModelApiData.Response), "Property is required for class ControllerWorkflooModelApiData.");

            if (controllerWorkflooModelApiData.RequestOption.IsSet)
            {
                writer.WritePropertyName("request");
                JsonSerializer.Serialize(writer, controllerWorkflooModelApiData.Request, jsonSerializerOptions);
            }
            if (controllerWorkflooModelApiData.ResponseOption.IsSet)
            {
                writer.WritePropertyName("response");
                JsonSerializer.Serialize(writer, controllerWorkflooModelApiData.Response, jsonSerializerOptions);
            }
        }
    }
}
