// <auto-generated>
/*
 * Workfloo API
 *
 * API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using kiban.sdk.workfloo.Client;

namespace kiban.sdk.workfloo.Model
{
    /// <summary>
    /// ControllerWorkflooModelNipResendRequest
    /// </summary>
    public partial class ControllerWorkflooModelNipResendRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ControllerWorkflooModelNipResendRequest" /> class.
        /// </summary>
        /// <param name="countryCode">countryCode</param>
        /// <param name="phoneNumber">phoneNumber</param>
        [JsonConstructor]
        public ControllerWorkflooModelNipResendRequest(Option<string?> countryCode = default, Option<string?> phoneNumber = default)
        {
            CountryCodeOption = countryCode;
            PhoneNumberOption = phoneNumber;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of CountryCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CountryCodeOption { get; private set; }

        /// <summary>
        /// Gets or Sets CountryCode
        /// </summary>
        [JsonPropertyName("countryCode")]
        public string? CountryCode { get { return this.CountryCodeOption.Value; } set { this.CountryCodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of PhoneNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PhoneNumberOption { get; private set; }

        /// <summary>
        /// Gets or Sets PhoneNumber
        /// </summary>
        [JsonPropertyName("phoneNumber")]
        public string? PhoneNumber { get { return this.PhoneNumberOption.Value; } set { this.PhoneNumberOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ControllerWorkflooModelNipResendRequest {\n");
            sb.Append("  CountryCode: ").Append(CountryCode).Append("\n");
            sb.Append("  PhoneNumber: ").Append(PhoneNumber).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ControllerWorkflooModelNipResendRequest" />
    /// </summary>
    public partial class ControllerWorkflooModelNipResendRequestJsonConverter : JsonConverter<ControllerWorkflooModelNipResendRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ControllerWorkflooModelNipResendRequestJsonConverter" /> class.
        /// </summary>
        public ControllerWorkflooModelNipResendRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ControllerWorkflooModelNipResendRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ControllerWorkflooModelNipResendRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> countryCode = default;
            Option<string?> phoneNumber = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "countryCode":
                            countryCode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "phoneNumber":
                            phoneNumber = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (countryCode.IsSet && countryCode.Value == null)
                throw new ArgumentNullException(nameof(countryCode), "Property is not nullable for class ControllerWorkflooModelNipResendRequest.");

            if (phoneNumber.IsSet && phoneNumber.Value == null)
                throw new ArgumentNullException(nameof(phoneNumber), "Property is not nullable for class ControllerWorkflooModelNipResendRequest.");

            return new ControllerWorkflooModelNipResendRequest(countryCode, phoneNumber);
        }

        /// <summary>
        /// Serializes a <see cref="ControllerWorkflooModelNipResendRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="controllerWorkflooModelNipResendRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ControllerWorkflooModelNipResendRequest controllerWorkflooModelNipResendRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, controllerWorkflooModelNipResendRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ControllerWorkflooModelNipResendRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="controllerWorkflooModelNipResendRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ControllerWorkflooModelNipResendRequest controllerWorkflooModelNipResendRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (controllerWorkflooModelNipResendRequest.CountryCodeOption.IsSet && controllerWorkflooModelNipResendRequest.CountryCode == null)
                throw new ArgumentNullException(nameof(controllerWorkflooModelNipResendRequest.CountryCode), "Property is required for class ControllerWorkflooModelNipResendRequest.");

            if (controllerWorkflooModelNipResendRequest.PhoneNumberOption.IsSet && controllerWorkflooModelNipResendRequest.PhoneNumber == null)
                throw new ArgumentNullException(nameof(controllerWorkflooModelNipResendRequest.PhoneNumber), "Property is required for class ControllerWorkflooModelNipResendRequest.");

            if (controllerWorkflooModelNipResendRequest.CountryCodeOption.IsSet)
                writer.WriteString("countryCode", controllerWorkflooModelNipResendRequest.CountryCode);

            if (controllerWorkflooModelNipResendRequest.PhoneNumberOption.IsSet)
                writer.WriteString("phoneNumber", controllerWorkflooModelNipResendRequest.PhoneNumber);
        }
    }
}
