// <auto-generated>
/*
 * Workfloo API
 *
 * API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using kiban.sdk.workfloo.Client;

namespace kiban.sdk.workfloo.Model
{
    /// <summary>
    /// ControllerWorkflooModelLinkNipStatus
    /// </summary>
    public partial class ControllerWorkflooModelLinkNipStatus : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ControllerWorkflooModelLinkNipStatus" /> class.
        /// </summary>
        /// <param name="companyName">companyName</param>
        /// <param name="countryCode">countryCode</param>
        /// <param name="email">email</param>
        /// <param name="events">events</param>
        /// <param name="key">key</param>
        /// <param name="keyTypeNode">keyTypeNode</param>
        /// <param name="nipType">nipType</param>
        /// <param name="phase">phase</param>
        /// <param name="phoneNumber">phoneNumber</param>
        /// <param name="privacyNotice">privacyNotice</param>
        /// <param name="terms">terms</param>
        /// <param name="widget">widget</param>
        [JsonConstructor]
        public ControllerWorkflooModelLinkNipStatus(Option<string?> companyName = default, Option<string?> countryCode = default, Option<string?> email = default, Option<List<ControllerWorkflooModelEvent>?> events = default, Option<string?> key = default, Option<string?> keyTypeNode = default, Option<string?> nipType = default, Option<string?> phase = default, Option<string?> phoneNumber = default, Option<string?> privacyNotice = default, Option<string?> terms = default, Option<Object?> widget = default)
        {
            CompanyNameOption = companyName;
            CountryCodeOption = countryCode;
            EmailOption = email;
            EventsOption = events;
            KeyOption = key;
            KeyTypeNodeOption = keyTypeNode;
            NipTypeOption = nipType;
            PhaseOption = phase;
            PhoneNumberOption = phoneNumber;
            PrivacyNoticeOption = privacyNotice;
            TermsOption = terms;
            WidgetOption = widget;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of CompanyName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CompanyNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets CompanyName
        /// </summary>
        [JsonPropertyName("companyName")]
        public string? CompanyName { get { return this.CompanyNameOption.Value; } set { this.CompanyNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of CountryCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CountryCodeOption { get; private set; }

        /// <summary>
        /// Gets or Sets CountryCode
        /// </summary>
        [JsonPropertyName("countryCode")]
        public string? CountryCode { get { return this.CountryCodeOption.Value; } set { this.CountryCodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Email
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EmailOption { get; private set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [JsonPropertyName("email")]
        public string? Email { get { return this.EmailOption.Value; } set { this.EmailOption = new(value); } }

        /// <summary>
        /// Used to track the state of Events
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<ControllerWorkflooModelEvent>?> EventsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Events
        /// </summary>
        [JsonPropertyName("events")]
        public List<ControllerWorkflooModelEvent>? Events { get { return this.EventsOption.Value; } set { this.EventsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Key
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> KeyOption { get; private set; }

        /// <summary>
        /// Gets or Sets Key
        /// </summary>
        [JsonPropertyName("key")]
        public string? Key { get { return this.KeyOption.Value; } set { this.KeyOption = new(value); } }

        /// <summary>
        /// Used to track the state of KeyTypeNode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> KeyTypeNodeOption { get; private set; }

        /// <summary>
        /// Gets or Sets KeyTypeNode
        /// </summary>
        [JsonPropertyName("keyTypeNode")]
        public string? KeyTypeNode { get { return this.KeyTypeNodeOption.Value; } set { this.KeyTypeNodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of NipType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NipTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets NipType
        /// </summary>
        [JsonPropertyName("nipType")]
        public string? NipType { get { return this.NipTypeOption.Value; } set { this.NipTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Phase
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PhaseOption { get; private set; }

        /// <summary>
        /// Gets or Sets Phase
        /// </summary>
        [JsonPropertyName("phase")]
        public string? Phase { get { return this.PhaseOption.Value; } set { this.PhaseOption = new(value); } }

        /// <summary>
        /// Used to track the state of PhoneNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PhoneNumberOption { get; private set; }

        /// <summary>
        /// Gets or Sets PhoneNumber
        /// </summary>
        [JsonPropertyName("phoneNumber")]
        public string? PhoneNumber { get { return this.PhoneNumberOption.Value; } set { this.PhoneNumberOption = new(value); } }

        /// <summary>
        /// Used to track the state of PrivacyNotice
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PrivacyNoticeOption { get; private set; }

        /// <summary>
        /// Gets or Sets PrivacyNotice
        /// </summary>
        [JsonPropertyName("privacyNotice")]
        public string? PrivacyNotice { get { return this.PrivacyNoticeOption.Value; } set { this.PrivacyNoticeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Terms
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TermsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Terms
        /// </summary>
        [JsonPropertyName("terms")]
        public string? Terms { get { return this.TermsOption.Value; } set { this.TermsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Widget
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> WidgetOption { get; private set; }

        /// <summary>
        /// Gets or Sets Widget
        /// </summary>
        [JsonPropertyName("widget")]
        public Object? Widget { get { return this.WidgetOption.Value; } set { this.WidgetOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ControllerWorkflooModelLinkNipStatus {\n");
            sb.Append("  CompanyName: ").Append(CompanyName).Append("\n");
            sb.Append("  CountryCode: ").Append(CountryCode).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Events: ").Append(Events).Append("\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  KeyTypeNode: ").Append(KeyTypeNode).Append("\n");
            sb.Append("  NipType: ").Append(NipType).Append("\n");
            sb.Append("  Phase: ").Append(Phase).Append("\n");
            sb.Append("  PhoneNumber: ").Append(PhoneNumber).Append("\n");
            sb.Append("  PrivacyNotice: ").Append(PrivacyNotice).Append("\n");
            sb.Append("  Terms: ").Append(Terms).Append("\n");
            sb.Append("  Widget: ").Append(Widget).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ControllerWorkflooModelLinkNipStatus" />
    /// </summary>
    public partial class ControllerWorkflooModelLinkNipStatusJsonConverter : JsonConverter<ControllerWorkflooModelLinkNipStatus>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ControllerWorkflooModelLinkNipStatusJsonConverter" /> class.
        /// </summary>
        public ControllerWorkflooModelLinkNipStatusJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ControllerWorkflooModelLinkNipStatus" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ControllerWorkflooModelLinkNipStatus Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> companyName = default;
            Option<string?> countryCode = default;
            Option<string?> email = default;
            Option<List<ControllerWorkflooModelEvent>?> events = default;
            Option<string?> key = default;
            Option<string?> keyTypeNode = default;
            Option<string?> nipType = default;
            Option<string?> phase = default;
            Option<string?> phoneNumber = default;
            Option<string?> privacyNotice = default;
            Option<string?> terms = default;
            Option<Object?> widget = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "companyName":
                            companyName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "countryCode":
                            countryCode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "email":
                            email = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "events":
                            events = new Option<List<ControllerWorkflooModelEvent>?>(JsonSerializer.Deserialize<List<ControllerWorkflooModelEvent>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "key":
                            key = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "keyTypeNode":
                            keyTypeNode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "nipType":
                            nipType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "phase":
                            phase = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "phoneNumber":
                            phoneNumber = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "privacyNotice":
                            privacyNotice = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "terms":
                            terms = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "widget":
                            widget = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (companyName.IsSet && companyName.Value == null)
                throw new ArgumentNullException(nameof(companyName), "Property is not nullable for class ControllerWorkflooModelLinkNipStatus.");

            if (countryCode.IsSet && countryCode.Value == null)
                throw new ArgumentNullException(nameof(countryCode), "Property is not nullable for class ControllerWorkflooModelLinkNipStatus.");

            if (email.IsSet && email.Value == null)
                throw new ArgumentNullException(nameof(email), "Property is not nullable for class ControllerWorkflooModelLinkNipStatus.");

            if (events.IsSet && events.Value == null)
                throw new ArgumentNullException(nameof(events), "Property is not nullable for class ControllerWorkflooModelLinkNipStatus.");

            if (key.IsSet && key.Value == null)
                throw new ArgumentNullException(nameof(key), "Property is not nullable for class ControllerWorkflooModelLinkNipStatus.");

            if (keyTypeNode.IsSet && keyTypeNode.Value == null)
                throw new ArgumentNullException(nameof(keyTypeNode), "Property is not nullable for class ControllerWorkflooModelLinkNipStatus.");

            if (nipType.IsSet && nipType.Value == null)
                throw new ArgumentNullException(nameof(nipType), "Property is not nullable for class ControllerWorkflooModelLinkNipStatus.");

            if (phase.IsSet && phase.Value == null)
                throw new ArgumentNullException(nameof(phase), "Property is not nullable for class ControllerWorkflooModelLinkNipStatus.");

            if (phoneNumber.IsSet && phoneNumber.Value == null)
                throw new ArgumentNullException(nameof(phoneNumber), "Property is not nullable for class ControllerWorkflooModelLinkNipStatus.");

            if (privacyNotice.IsSet && privacyNotice.Value == null)
                throw new ArgumentNullException(nameof(privacyNotice), "Property is not nullable for class ControllerWorkflooModelLinkNipStatus.");

            if (terms.IsSet && terms.Value == null)
                throw new ArgumentNullException(nameof(terms), "Property is not nullable for class ControllerWorkflooModelLinkNipStatus.");

            return new ControllerWorkflooModelLinkNipStatus(companyName, countryCode, email, events, key, keyTypeNode, nipType, phase, phoneNumber, privacyNotice, terms, widget);
        }

        /// <summary>
        /// Serializes a <see cref="ControllerWorkflooModelLinkNipStatus" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="controllerWorkflooModelLinkNipStatus"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ControllerWorkflooModelLinkNipStatus controllerWorkflooModelLinkNipStatus, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, controllerWorkflooModelLinkNipStatus, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ControllerWorkflooModelLinkNipStatus" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="controllerWorkflooModelLinkNipStatus"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ControllerWorkflooModelLinkNipStatus controllerWorkflooModelLinkNipStatus, JsonSerializerOptions jsonSerializerOptions)
        {
            if (controllerWorkflooModelLinkNipStatus.CompanyNameOption.IsSet && controllerWorkflooModelLinkNipStatus.CompanyName == null)
                throw new ArgumentNullException(nameof(controllerWorkflooModelLinkNipStatus.CompanyName), "Property is required for class ControllerWorkflooModelLinkNipStatus.");

            if (controllerWorkflooModelLinkNipStatus.CountryCodeOption.IsSet && controllerWorkflooModelLinkNipStatus.CountryCode == null)
                throw new ArgumentNullException(nameof(controllerWorkflooModelLinkNipStatus.CountryCode), "Property is required for class ControllerWorkflooModelLinkNipStatus.");

            if (controllerWorkflooModelLinkNipStatus.EmailOption.IsSet && controllerWorkflooModelLinkNipStatus.Email == null)
                throw new ArgumentNullException(nameof(controllerWorkflooModelLinkNipStatus.Email), "Property is required for class ControllerWorkflooModelLinkNipStatus.");

            if (controllerWorkflooModelLinkNipStatus.EventsOption.IsSet && controllerWorkflooModelLinkNipStatus.Events == null)
                throw new ArgumentNullException(nameof(controllerWorkflooModelLinkNipStatus.Events), "Property is required for class ControllerWorkflooModelLinkNipStatus.");

            if (controllerWorkflooModelLinkNipStatus.KeyOption.IsSet && controllerWorkflooModelLinkNipStatus.Key == null)
                throw new ArgumentNullException(nameof(controllerWorkflooModelLinkNipStatus.Key), "Property is required for class ControllerWorkflooModelLinkNipStatus.");

            if (controllerWorkflooModelLinkNipStatus.KeyTypeNodeOption.IsSet && controllerWorkflooModelLinkNipStatus.KeyTypeNode == null)
                throw new ArgumentNullException(nameof(controllerWorkflooModelLinkNipStatus.KeyTypeNode), "Property is required for class ControllerWorkflooModelLinkNipStatus.");

            if (controllerWorkflooModelLinkNipStatus.NipTypeOption.IsSet && controllerWorkflooModelLinkNipStatus.NipType == null)
                throw new ArgumentNullException(nameof(controllerWorkflooModelLinkNipStatus.NipType), "Property is required for class ControllerWorkflooModelLinkNipStatus.");

            if (controllerWorkflooModelLinkNipStatus.PhaseOption.IsSet && controllerWorkflooModelLinkNipStatus.Phase == null)
                throw new ArgumentNullException(nameof(controllerWorkflooModelLinkNipStatus.Phase), "Property is required for class ControllerWorkflooModelLinkNipStatus.");

            if (controllerWorkflooModelLinkNipStatus.PhoneNumberOption.IsSet && controllerWorkflooModelLinkNipStatus.PhoneNumber == null)
                throw new ArgumentNullException(nameof(controllerWorkflooModelLinkNipStatus.PhoneNumber), "Property is required for class ControllerWorkflooModelLinkNipStatus.");

            if (controllerWorkflooModelLinkNipStatus.PrivacyNoticeOption.IsSet && controllerWorkflooModelLinkNipStatus.PrivacyNotice == null)
                throw new ArgumentNullException(nameof(controllerWorkflooModelLinkNipStatus.PrivacyNotice), "Property is required for class ControllerWorkflooModelLinkNipStatus.");

            if (controllerWorkflooModelLinkNipStatus.TermsOption.IsSet && controllerWorkflooModelLinkNipStatus.Terms == null)
                throw new ArgumentNullException(nameof(controllerWorkflooModelLinkNipStatus.Terms), "Property is required for class ControllerWorkflooModelLinkNipStatus.");

            if (controllerWorkflooModelLinkNipStatus.CompanyNameOption.IsSet)
                writer.WriteString("companyName", controllerWorkflooModelLinkNipStatus.CompanyName);

            if (controllerWorkflooModelLinkNipStatus.CountryCodeOption.IsSet)
                writer.WriteString("countryCode", controllerWorkflooModelLinkNipStatus.CountryCode);

            if (controllerWorkflooModelLinkNipStatus.EmailOption.IsSet)
                writer.WriteString("email", controllerWorkflooModelLinkNipStatus.Email);

            if (controllerWorkflooModelLinkNipStatus.EventsOption.IsSet)
            {
                writer.WritePropertyName("events");
                JsonSerializer.Serialize(writer, controllerWorkflooModelLinkNipStatus.Events, jsonSerializerOptions);
            }
            if (controllerWorkflooModelLinkNipStatus.KeyOption.IsSet)
                writer.WriteString("key", controllerWorkflooModelLinkNipStatus.Key);

            if (controllerWorkflooModelLinkNipStatus.KeyTypeNodeOption.IsSet)
                writer.WriteString("keyTypeNode", controllerWorkflooModelLinkNipStatus.KeyTypeNode);

            if (controllerWorkflooModelLinkNipStatus.NipTypeOption.IsSet)
                writer.WriteString("nipType", controllerWorkflooModelLinkNipStatus.NipType);

            if (controllerWorkflooModelLinkNipStatus.PhaseOption.IsSet)
                writer.WriteString("phase", controllerWorkflooModelLinkNipStatus.Phase);

            if (controllerWorkflooModelLinkNipStatus.PhoneNumberOption.IsSet)
                writer.WriteString("phoneNumber", controllerWorkflooModelLinkNipStatus.PhoneNumber);

            if (controllerWorkflooModelLinkNipStatus.PrivacyNoticeOption.IsSet)
                writer.WriteString("privacyNotice", controllerWorkflooModelLinkNipStatus.PrivacyNotice);

            if (controllerWorkflooModelLinkNipStatus.TermsOption.IsSet)
                writer.WriteString("terms", controllerWorkflooModelLinkNipStatus.Terms);

            if (controllerWorkflooModelLinkNipStatus.WidgetOption.IsSet)
                if (controllerWorkflooModelLinkNipStatus.WidgetOption.Value != null)
                {
                    writer.WritePropertyName("widget");
                    JsonSerializer.Serialize(writer, controllerWorkflooModelLinkNipStatus.Widget, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("widget");
        }
    }
}
