# coding: utf-8

"""
    Workfloo API

    API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.

    The version of the OpenAPI document: 1.0
    Contact: hola@kiban.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from kiban.workfloo.models.controller_workfloo_definition_model_document import ControllerWorkflooDefinitionModelDocument
from kiban.workfloo.models.controller_workfloo_definition_model_form import ControllerWorkflooDefinitionModelForm
from kiban.workfloo.models.controller_workfloo_model_link_nip_status import ControllerWorkflooModelLinkNipStatus
from kiban.workfloo.models.controller_workfloo_model_timer import ControllerWorkflooModelTimer
from kiban.workfloo.models.controller_workfloo_model_validation_status import ControllerWorkflooModelValidationStatus
from kiban.workfloo.models.controller_workfloo_model_verification_status import ControllerWorkflooModelVerificationStatus
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ControllerWorkflooModelWorkflooStatus(BaseModel):
    """
    ControllerWorkflooModelWorkflooStatus
    """ # noqa: E501
    cancelled_at: Optional[StrictStr] = Field(default=None, alias="cancelledAt")
    cancelled_by: Optional[StrictStr] = Field(default=None, description="Rastro de la cancelación manual, ausente en cualquier otro desenlace. Mismas dos reglas que en WorkflooResume: sólo la cancelación desde la consola los llena, y la fecha es un puntero para que omitempty funcione.", alias="cancelledBy")
    current_node_id: Optional[StrictStr] = Field(default=None, alias="currentNodeId")
    current_node_name: Optional[StrictStr] = Field(default=None, alias="currentNodeName")
    current_node_type: Optional[StrictStr] = Field(default=None, alias="currentNodeType")
    document: Optional[ControllerWorkflooDefinitionModelDocument] = None
    form: Optional[ControllerWorkflooDefinitionModelForm] = None
    id: Optional[StrictStr] = None
    link: Optional[ControllerWorkflooModelLinkNipStatus] = None
    name: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    timer: Optional[ControllerWorkflooModelTimer] = None
    validation: Optional[ControllerWorkflooModelValidationStatus] = None
    verification: Optional[ControllerWorkflooModelVerificationStatus] = Field(default=None, description="Verification aparece SÓLO cuando la ejecución está esperando que alguien teclee un código. Su ausencia es lo que le dice al integrador que no hay nada pendiente de ese lado.")
    __properties: ClassVar[List[str]] = ["cancelledAt", "cancelledBy", "currentNodeId", "currentNodeName", "currentNodeType", "document", "form", "id", "link", "name", "status", "timer", "validation", "verification"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ControllerWorkflooModelWorkflooStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of document
        if self.document:
            _dict['document'] = self.document.to_dict()
        # override the default output from pydantic by calling `to_dict()` of form
        if self.form:
            _dict['form'] = self.form.to_dict()
        # override the default output from pydantic by calling `to_dict()` of link
        if self.link:
            _dict['link'] = self.link.to_dict()
        # override the default output from pydantic by calling `to_dict()` of timer
        if self.timer:
            _dict['timer'] = self.timer.to_dict()
        # override the default output from pydantic by calling `to_dict()` of validation
        if self.validation:
            _dict['validation'] = self.validation.to_dict()
        # override the default output from pydantic by calling `to_dict()` of verification
        if self.verification:
            _dict['verification'] = self.verification.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ControllerWorkflooModelWorkflooStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cancelledAt": obj.get("cancelledAt"),
            "cancelledBy": obj.get("cancelledBy"),
            "currentNodeId": obj.get("currentNodeId"),
            "currentNodeName": obj.get("currentNodeName"),
            "currentNodeType": obj.get("currentNodeType"),
            "document": ControllerWorkflooDefinitionModelDocument.from_dict(obj["document"]) if obj.get("document") is not None else None,
            "form": ControllerWorkflooDefinitionModelForm.from_dict(obj["form"]) if obj.get("form") is not None else None,
            "id": obj.get("id"),
            "link": ControllerWorkflooModelLinkNipStatus.from_dict(obj["link"]) if obj.get("link") is not None else None,
            "name": obj.get("name"),
            "status": obj.get("status"),
            "timer": ControllerWorkflooModelTimer.from_dict(obj["timer"]) if obj.get("timer") is not None else None,
            "validation": ControllerWorkflooModelValidationStatus.from_dict(obj["validation"]) if obj.get("validation") is not None else None,
            "verification": ControllerWorkflooModelVerificationStatus.from_dict(obj["verification"]) if obj.get("verification") is not None else None
        })
        return _obj


