/*
 * Workfloo API
 *
 * API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using kiban.sdk.workfloo.Api;
using kiban.sdk.workfloo.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace kiban.sdk.workfloo.Test.Api
{
    /// <summary>
    ///  Class for testing WorkflooApi
    /// </summary>
    public sealed class WorkflooApiTests : ApiTestsBase
    {
        private readonly IWorkflooApi _instance;

        public WorkflooApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IWorkflooApi>();
        }

        /// <summary>
        /// Test ExecuteWorkfloo
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ExecuteWorkflooAsyncTest()
        {
            ControllerWorkflooModelExecute controllerWorkflooModelExecute = default!;
            Client.Option<bool> sandbox = default!;
            var response = await _instance.ExecuteWorkflooAsync(controllerWorkflooModelExecute, sandbox);
            var model = response.Ok();
            Assert.IsType<ControllerWorkflooModelExecuteResponse>(model);
        }

        /// <summary>
        /// Test GetWorkfloo
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetWorkflooAsyncTest()
        {
            string id = default!;
            Client.Option<bool> sandbox = default!;
            var response = await _instance.GetWorkflooAsync(id, sandbox);
            var model = response.Ok();
            Assert.IsType<ControllerWorkflooModelWorkflooResume>(model);
        }

        /// <summary>
        /// Test GetWorkflooStatus
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetWorkflooStatusAsyncTest()
        {
            string id = default!;
            Client.Option<bool> sandbox = default!;
            var response = await _instance.GetWorkflooStatusAsync(id, sandbox);
            var model = response.Ok();
            Assert.IsType<ControllerWorkflooModelWorkflooStatus>(model);
        }

        /// <summary>
        /// Test ListWorkfloos
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ListWorkfloosAsyncTest()
        {
            int page = default!;
            int itemsPerPage = default!;
            Client.Option<string> status = default!;
            Client.Option<string> from = default!;
            Client.Option<string> to = default!;
            Client.Option<bool> sandbox = default!;
            var response = await _instance.ListWorkfloosAsync(page, itemsPerPage, status, from, to, sandbox);
            var model = response.Ok();
            Assert.IsType<ControllerWorkflooModelWorkflooPage>(model);
        }

        /// <summary>
        /// Test ListWorkfloosV2
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ListWorkfloosV2AsyncTest()
        {
            Client.Option<int> page = default!;
            Client.Option<int> itemsPerPage = default!;
            Client.Option<string> status = default!;
            Client.Option<string> from = default!;
            Client.Option<string> to = default!;
            Client.Option<string> format = default!;
            Client.Option<bool> sandbox = default!;
            var response = await _instance.ListWorkfloosV2Async(page, itemsPerPage, status, from, to, format, sandbox);
            var model = response.Ok();
            Assert.IsType<List<ControllerWorkflooModelWorkfloo>>(model);
        }
    }
}
