/*
Link API

API pública de Link (Kiban): ejecuta un servicio de consulta/validación del catálogo Link (curp, sat, imss, nip, sms, buró de crédito, etc.), consulta su resultado y revisa el historial de ejecuciones.  Link expone un conjunto de endpoints genéricos: el servicio a ejecutar se elige en la ruta con {service}/{subservice}. El cuerpo de la petición y la forma de la respuesta dependen del servicio elegido; cada servicio define sus propios campos. Consulta el catálogo de servicios para el detalle de cada uno. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://link.kiban.com y sandbox en https://sandbox.link.kiban.com. En sandbox la ejecución no llama al proveedor real: devuelve un test case configurable, para que puedas integrar el contrato del servicio sin costo ni credenciales reales.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package link

import (
	"encoding/json"
)

// checks if the ControllerMicroserviceModelApiDataFileDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ControllerMicroserviceModelApiDataFileDto{}

// ControllerMicroserviceModelApiDataFileDto struct for ControllerMicroserviceModelApiDataFileDto
type ControllerMicroserviceModelApiDataFileDto struct {
	Content []int32 `json:"content,omitempty"`
	Name *string `json:"name,omitempty"`
	Path *string `json:"path,omitempty"`
}

// NewControllerMicroserviceModelApiDataFileDto instantiates a new ControllerMicroserviceModelApiDataFileDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewControllerMicroserviceModelApiDataFileDto() *ControllerMicroserviceModelApiDataFileDto {
	this := ControllerMicroserviceModelApiDataFileDto{}
	return &this
}

// NewControllerMicroserviceModelApiDataFileDtoWithDefaults instantiates a new ControllerMicroserviceModelApiDataFileDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewControllerMicroserviceModelApiDataFileDtoWithDefaults() *ControllerMicroserviceModelApiDataFileDto {
	this := ControllerMicroserviceModelApiDataFileDto{}
	return &this
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *ControllerMicroserviceModelApiDataFileDto) GetContent() []int32 {
	if o == nil || IsNil(o.Content) {
		var ret []int32
		return ret
	}
	return o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerMicroserviceModelApiDataFileDto) GetContentOk() ([]int32, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *ControllerMicroserviceModelApiDataFileDto) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given []int32 and assigns it to the Content field.
func (o *ControllerMicroserviceModelApiDataFileDto) SetContent(v []int32) {
	o.Content = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ControllerMicroserviceModelApiDataFileDto) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerMicroserviceModelApiDataFileDto) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ControllerMicroserviceModelApiDataFileDto) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ControllerMicroserviceModelApiDataFileDto) SetName(v string) {
	o.Name = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *ControllerMicroserviceModelApiDataFileDto) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerMicroserviceModelApiDataFileDto) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *ControllerMicroserviceModelApiDataFileDto) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *ControllerMicroserviceModelApiDataFileDto) SetPath(v string) {
	o.Path = &v
}

func (o ControllerMicroserviceModelApiDataFileDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ControllerMicroserviceModelApiDataFileDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	return toSerialize, nil
}

type NullableControllerMicroserviceModelApiDataFileDto struct {
	value *ControllerMicroserviceModelApiDataFileDto
	isSet bool
}

func (v NullableControllerMicroserviceModelApiDataFileDto) Get() *ControllerMicroserviceModelApiDataFileDto {
	return v.value
}

func (v *NullableControllerMicroserviceModelApiDataFileDto) Set(val *ControllerMicroserviceModelApiDataFileDto) {
	v.value = val
	v.isSet = true
}

func (v NullableControllerMicroserviceModelApiDataFileDto) IsSet() bool {
	return v.isSet
}

func (v *NullableControllerMicroserviceModelApiDataFileDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableControllerMicroserviceModelApiDataFileDto(val *ControllerMicroserviceModelApiDataFileDto) *NullableControllerMicroserviceModelApiDataFileDto {
	return &NullableControllerMicroserviceModelApiDataFileDto{value: val, isSet: true}
}

func (v NullableControllerMicroserviceModelApiDataFileDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableControllerMicroserviceModelApiDataFileDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


