// <auto-generated>
/*
 * Link API
 *
 * API pública de Link (Kiban): ejecuta un servicio de consulta/validación del catálogo Link (curp, sat, imss, nip, sms, buró de crédito, etc.), consulta su resultado y revisa el historial de ejecuciones.  Link expone un conjunto de endpoints genéricos: el servicio a ejecutar se elige en la ruta con {service}/{subservice}. El cuerpo de la petición y la forma de la respuesta dependen del servicio elegido; cada servicio define sus propios campos. Consulta el catálogo de servicios para el detalle de cada uno. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://link.kiban.com y sandbox en https://sandbox.link.kiban.com. En sandbox la ejecución no llama al proveedor real: devuelve un test case configurable, para que puedas integrar el contrato del servicio sin costo ni credenciales reales.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using kiban.sdk.link.Client;

namespace kiban.sdk.link.Model
{
    /// <summary>
    /// ControllerMicroserviceModelApiDataHttpDto
    /// </summary>
    public partial class ControllerMicroserviceModelApiDataHttpDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ControllerMicroserviceModelApiDataHttpDto" /> class.
        /// </summary>
        /// <param name="body">body</param>
        /// <param name="date">date</param>
        /// <param name="headers">headers</param>
        /// <param name="httpCode">httpCode</param>
        [JsonConstructor]
        public ControllerMicroserviceModelApiDataHttpDto(Option<Object?> body = default, Option<string?> date = default, Option<Dictionary<string, string>?> headers = default, Option<int?> httpCode = default)
        {
            BodyOption = body;
            DateOption = date;
            HeadersOption = headers;
            HttpCodeOption = httpCode;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Body
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> BodyOption { get; private set; }

        /// <summary>
        /// Gets or Sets Body
        /// </summary>
        [JsonPropertyName("body")]
        public Object? Body { get { return this.BodyOption.Value; } set { this.BodyOption = new(value); } }

        /// <summary>
        /// Used to track the state of Date
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DateOption { get; private set; }

        /// <summary>
        /// Gets or Sets Date
        /// </summary>
        [JsonPropertyName("date")]
        public string? Date { get { return this.DateOption.Value; } set { this.DateOption = new(value); } }

        /// <summary>
        /// Used to track the state of Headers
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, string>?> HeadersOption { get; private set; }

        /// <summary>
        /// Gets or Sets Headers
        /// </summary>
        [JsonPropertyName("headers")]
        public Dictionary<string, string>? Headers { get { return this.HeadersOption.Value; } set { this.HeadersOption = new(value); } }

        /// <summary>
        /// Used to track the state of HttpCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> HttpCodeOption { get; private set; }

        /// <summary>
        /// Gets or Sets HttpCode
        /// </summary>
        [JsonPropertyName("httpCode")]
        public int? HttpCode { get { return this.HttpCodeOption.Value; } set { this.HttpCodeOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ControllerMicroserviceModelApiDataHttpDto {\n");
            sb.Append("  Body: ").Append(Body).Append("\n");
            sb.Append("  Date: ").Append(Date).Append("\n");
            sb.Append("  Headers: ").Append(Headers).Append("\n");
            sb.Append("  HttpCode: ").Append(HttpCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ControllerMicroserviceModelApiDataHttpDto" />
    /// </summary>
    public partial class ControllerMicroserviceModelApiDataHttpDtoJsonConverter : JsonConverter<ControllerMicroserviceModelApiDataHttpDto>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ControllerMicroserviceModelApiDataHttpDtoJsonConverter" /> class.
        /// </summary>
        public ControllerMicroserviceModelApiDataHttpDtoJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ControllerMicroserviceModelApiDataHttpDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ControllerMicroserviceModelApiDataHttpDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Object?> body = default;
            Option<string?> date = default;
            Option<Dictionary<string, string>?> headers = default;
            Option<int?> httpCode = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "body":
                            body = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "date":
                            date = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "headers":
                            headers = new Option<Dictionary<string, string>?>(JsonSerializer.Deserialize<Dictionary<string, string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "httpCode":
                            httpCode = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (date.IsSet && date.Value == null)
                throw new ArgumentNullException(nameof(date), "Property is not nullable for class ControllerMicroserviceModelApiDataHttpDto.");

            if (headers.IsSet && headers.Value == null)
                throw new ArgumentNullException(nameof(headers), "Property is not nullable for class ControllerMicroserviceModelApiDataHttpDto.");

            if (httpCode.IsSet && httpCode.Value == null)
                throw new ArgumentNullException(nameof(httpCode), "Property is not nullable for class ControllerMicroserviceModelApiDataHttpDto.");

            return new ControllerMicroserviceModelApiDataHttpDto(body, date, headers, httpCode);
        }

        /// <summary>
        /// Serializes a <see cref="ControllerMicroserviceModelApiDataHttpDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="controllerMicroserviceModelApiDataHttpDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ControllerMicroserviceModelApiDataHttpDto controllerMicroserviceModelApiDataHttpDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, controllerMicroserviceModelApiDataHttpDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ControllerMicroserviceModelApiDataHttpDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="controllerMicroserviceModelApiDataHttpDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ControllerMicroserviceModelApiDataHttpDto controllerMicroserviceModelApiDataHttpDto, JsonSerializerOptions jsonSerializerOptions)
        {
            if (controllerMicroserviceModelApiDataHttpDto.DateOption.IsSet && controllerMicroserviceModelApiDataHttpDto.Date == null)
                throw new ArgumentNullException(nameof(controllerMicroserviceModelApiDataHttpDto.Date), "Property is required for class ControllerMicroserviceModelApiDataHttpDto.");

            if (controllerMicroserviceModelApiDataHttpDto.HeadersOption.IsSet && controllerMicroserviceModelApiDataHttpDto.Headers == null)
                throw new ArgumentNullException(nameof(controllerMicroserviceModelApiDataHttpDto.Headers), "Property is required for class ControllerMicroserviceModelApiDataHttpDto.");

            if (controllerMicroserviceModelApiDataHttpDto.BodyOption.IsSet)
                if (controllerMicroserviceModelApiDataHttpDto.BodyOption.Value != null)
                {
                    writer.WritePropertyName("body");
                    JsonSerializer.Serialize(writer, controllerMicroserviceModelApiDataHttpDto.Body, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("body");
            if (controllerMicroserviceModelApiDataHttpDto.DateOption.IsSet)
                writer.WriteString("date", controllerMicroserviceModelApiDataHttpDto.Date);

            if (controllerMicroserviceModelApiDataHttpDto.HeadersOption.IsSet)
            {
                writer.WritePropertyName("headers");
                JsonSerializer.Serialize(writer, controllerMicroserviceModelApiDataHttpDto.Headers, jsonSerializerOptions);
            }
            if (controllerMicroserviceModelApiDataHttpDto.HttpCodeOption.IsSet)
                writer.WriteNumber("httpCode", controllerMicroserviceModelApiDataHttpDto.HttpCodeOption.Value!.Value);
        }
    }
}
