/*
 * Workfloo API
 * API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package kiban.sdk.workfloo.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import kiban.sdk.workfloo.model.ControllerWorkflooDefinitionModelFieldMetadata;
import kiban.sdk.workfloo.model.ControllerWorkflooDefinitionModelSetData;
import kiban.sdk.workfloo.model.ControllerWorkflooDefinitionModelShowIf;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import kiban.sdk.workfloo.JSON;

/**
 * ControllerWorkflooDefinitionModelField
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-10T16:42:49.836741-06:00[America/Mexico_City]", comments = "Generator version: 7.24.0")
public class ControllerWorkflooDefinitionModelField {
  public static final String SERIALIZED_NAME_FIELD_METADATA = "fieldMetadata";
  @SerializedName(SERIALIZED_NAME_FIELD_METADATA)
  @javax.annotation.Nullable
  private ControllerWorkflooDefinitionModelFieldMetadata fieldMetadata;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_PREDEFINED = "predefined";
  @SerializedName(SERIALIZED_NAME_PREDEFINED)
  @javax.annotation.Nullable
  private Boolean predefined;

  public static final String SERIALIZED_NAME_REQUIRED = "required";
  @SerializedName(SERIALIZED_NAME_REQUIRED)
  @javax.annotation.Nullable
  private Boolean required;

  public static final String SERIALIZED_NAME_SECTION = "section";
  @SerializedName(SERIALIZED_NAME_SECTION)
  @javax.annotation.Nullable
  private String section;

  public static final String SERIALIZED_NAME_SET = "set";
  @SerializedName(SERIALIZED_NAME_SET)
  @javax.annotation.Nullable
  private ControllerWorkflooDefinitionModelSetData set;

  public static final String SERIALIZED_NAME_SHOW_IF = "showIf";
  @SerializedName(SERIALIZED_NAME_SHOW_IF)
  @javax.annotation.Nullable
  private List<ControllerWorkflooDefinitionModelShowIf> showIf = new ArrayList<>();

  public ControllerWorkflooDefinitionModelField() {
  }

  public ControllerWorkflooDefinitionModelField fieldMetadata(@javax.annotation.Nullable ControllerWorkflooDefinitionModelFieldMetadata fieldMetadata) {
    this.fieldMetadata = fieldMetadata;
    return this;
  }

  /**
   * Get fieldMetadata
   * @return fieldMetadata
   */
  @javax.annotation.Nullable
  public ControllerWorkflooDefinitionModelFieldMetadata getFieldMetadata() {
    return fieldMetadata;
  }

  public void setFieldMetadata(@javax.annotation.Nullable ControllerWorkflooDefinitionModelFieldMetadata fieldMetadata) {
    this.fieldMetadata = fieldMetadata;
  }


  public ControllerWorkflooDefinitionModelField id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public ControllerWorkflooDefinitionModelField name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public ControllerWorkflooDefinitionModelField predefined(@javax.annotation.Nullable Boolean predefined) {
    this.predefined = predefined;
    return this;
  }

  /**
   * Get predefined
   * @return predefined
   */
  @javax.annotation.Nullable
  public Boolean getPredefined() {
    return predefined;
  }

  public void setPredefined(@javax.annotation.Nullable Boolean predefined) {
    this.predefined = predefined;
  }


  public ControllerWorkflooDefinitionModelField required(@javax.annotation.Nullable Boolean required) {
    this.required = required;
    return this;
  }

  /**
   * Get required
   * @return required
   */
  @javax.annotation.Nullable
  public Boolean getRequired() {
    return required;
  }

  public void setRequired(@javax.annotation.Nullable Boolean required) {
    this.required = required;
  }


  public ControllerWorkflooDefinitionModelField section(@javax.annotation.Nullable String section) {
    this.section = section;
    return this;
  }

  /**
   * Get section
   * @return section
   */
  @javax.annotation.Nullable
  public String getSection() {
    return section;
  }

  public void setSection(@javax.annotation.Nullable String section) {
    this.section = section;
  }


  public ControllerWorkflooDefinitionModelField set(@javax.annotation.Nullable ControllerWorkflooDefinitionModelSetData set) {
    this.set = set;
    return this;
  }

  /**
   * Get set
   * @return set
   */
  @javax.annotation.Nullable
  public ControllerWorkflooDefinitionModelSetData getSet() {
    return set;
  }

  public void setSet(@javax.annotation.Nullable ControllerWorkflooDefinitionModelSetData set) {
    this.set = set;
  }


  public ControllerWorkflooDefinitionModelField showIf(@javax.annotation.Nullable List<ControllerWorkflooDefinitionModelShowIf> showIf) {
    this.showIf = showIf;
    return this;
  }

  public ControllerWorkflooDefinitionModelField addShowIfItem(ControllerWorkflooDefinitionModelShowIf showIfItem) {
    if (this.showIf == null) {
      this.showIf = new ArrayList<>();
    }
    this.showIf.add(showIfItem);
    return this;
  }

  /**
   * Get showIf
   * @return showIf
   */
  @javax.annotation.Nullable
  public List<ControllerWorkflooDefinitionModelShowIf> getShowIf() {
    return showIf;
  }

  public void setShowIf(@javax.annotation.Nullable List<ControllerWorkflooDefinitionModelShowIf> showIf) {
    this.showIf = showIf;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ControllerWorkflooDefinitionModelField controllerWorkflooDefinitionModelField = (ControllerWorkflooDefinitionModelField) o;
    return Objects.equals(this.fieldMetadata, controllerWorkflooDefinitionModelField.fieldMetadata) &&
        Objects.equals(this.id, controllerWorkflooDefinitionModelField.id) &&
        Objects.equals(this.name, controllerWorkflooDefinitionModelField.name) &&
        Objects.equals(this.predefined, controllerWorkflooDefinitionModelField.predefined) &&
        Objects.equals(this.required, controllerWorkflooDefinitionModelField.required) &&
        Objects.equals(this.section, controllerWorkflooDefinitionModelField.section) &&
        Objects.equals(this.set, controllerWorkflooDefinitionModelField.set) &&
        Objects.equals(this.showIf, controllerWorkflooDefinitionModelField.showIf);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fieldMetadata, id, name, predefined, required, section, set, showIf);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ControllerWorkflooDefinitionModelField {\n");
    sb.append("    fieldMetadata: ").append(toIndentedString(fieldMetadata)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    predefined: ").append(toIndentedString(predefined)).append("\n");
    sb.append("    required: ").append(toIndentedString(required)).append("\n");
    sb.append("    section: ").append(toIndentedString(section)).append("\n");
    sb.append("    set: ").append(toIndentedString(set)).append("\n");
    sb.append("    showIf: ").append(toIndentedString(showIf)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("fieldMetadata", "id", "name", "predefined", "required", "section", "set", "showIf"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ControllerWorkflooDefinitionModelField
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ControllerWorkflooDefinitionModelField.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ControllerWorkflooDefinitionModelField is not found in the empty JSON string", ControllerWorkflooDefinitionModelField.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ControllerWorkflooDefinitionModelField.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ControllerWorkflooDefinitionModelField` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `fieldMetadata`
      if (jsonObj.get("fieldMetadata") != null && !jsonObj.get("fieldMetadata").isJsonNull()) {
        ControllerWorkflooDefinitionModelFieldMetadata.validateJsonElement(jsonObj.get("fieldMetadata"));
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("section") != null && !jsonObj.get("section").isJsonNull()) && !jsonObj.get("section").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `section` to be a primitive type in the JSON string but got `%s`", jsonObj.get("section").toString()));
      }
      // validate the optional field `set`
      if (jsonObj.get("set") != null && !jsonObj.get("set").isJsonNull()) {
        ControllerWorkflooDefinitionModelSetData.validateJsonElement(jsonObj.get("set"));
      }
      if (jsonObj.get("showIf") != null && !jsonObj.get("showIf").isJsonNull()) {
        JsonArray jsonArrayshowIf = jsonObj.getAsJsonArray("showIf");
        if (jsonArrayshowIf != null) {
          // ensure the json data is an array
          if (!jsonObj.get("showIf").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `showIf` to be an array in the JSON string but got `%s`", jsonObj.get("showIf").toString()));
          }

          // validate the optional field `showIf` (array)
          for (int i = 0; i < jsonArrayshowIf.size(); i++) {
            ControllerWorkflooDefinitionModelShowIf.validateJsonElement(jsonArrayshowIf.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ControllerWorkflooDefinitionModelField.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ControllerWorkflooDefinitionModelField' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ControllerWorkflooDefinitionModelField> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ControllerWorkflooDefinitionModelField.class));

       return (TypeAdapter<T>) new TypeAdapter<ControllerWorkflooDefinitionModelField>() {
           @Override
           public void write(JsonWriter out, ControllerWorkflooDefinitionModelField value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ControllerWorkflooDefinitionModelField read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ControllerWorkflooDefinitionModelField given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ControllerWorkflooDefinitionModelField
   * @throws IOException if the JSON string is invalid with respect to ControllerWorkflooDefinitionModelField
   */
  public static ControllerWorkflooDefinitionModelField fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ControllerWorkflooDefinitionModelField.class);
  }

  /**
   * Convert an instance of ControllerWorkflooDefinitionModelField to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

