/*
 * Workfloo API
 * API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package kiban.sdk.workfloo.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import kiban.sdk.workfloo.model.ControllerWorkflooModelRemainingTime;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import kiban.sdk.workfloo.JSON;

/**
 * ControllerWorkflooModelTimer
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-23T16:41:40.675919-06:00[America/Mexico_City]", comments = "Generator version: 7.24.0")
public class ControllerWorkflooModelTimer {
  public static final String SERIALIZED_NAME_END_WAIT_DATE = "endWaitDate";
  @SerializedName(SERIALIZED_NAME_END_WAIT_DATE)
  @javax.annotation.Nullable
  private String endWaitDate;

  public static final String SERIALIZED_NAME_REMAINING_TIME = "remainingTime";
  @SerializedName(SERIALIZED_NAME_REMAINING_TIME)
  @javax.annotation.Nullable
  private ControllerWorkflooModelRemainingTime remainingTime;

  public ControllerWorkflooModelTimer() {
  }

  public ControllerWorkflooModelTimer endWaitDate(@javax.annotation.Nullable String endWaitDate) {
    this.endWaitDate = endWaitDate;
    return this;
  }

  /**
   * Get endWaitDate
   * @return endWaitDate
   */
  @javax.annotation.Nullable
  public String getEndWaitDate() {
    return endWaitDate;
  }

  public void setEndWaitDate(@javax.annotation.Nullable String endWaitDate) {
    this.endWaitDate = endWaitDate;
  }


  public ControllerWorkflooModelTimer remainingTime(@javax.annotation.Nullable ControllerWorkflooModelRemainingTime remainingTime) {
    this.remainingTime = remainingTime;
    return this;
  }

  /**
   * Get remainingTime
   * @return remainingTime
   */
  @javax.annotation.Nullable
  public ControllerWorkflooModelRemainingTime getRemainingTime() {
    return remainingTime;
  }

  public void setRemainingTime(@javax.annotation.Nullable ControllerWorkflooModelRemainingTime remainingTime) {
    this.remainingTime = remainingTime;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ControllerWorkflooModelTimer controllerWorkflooModelTimer = (ControllerWorkflooModelTimer) o;
    return Objects.equals(this.endWaitDate, controllerWorkflooModelTimer.endWaitDate) &&
        Objects.equals(this.remainingTime, controllerWorkflooModelTimer.remainingTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(endWaitDate, remainingTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ControllerWorkflooModelTimer {\n");
    sb.append("    endWaitDate: ").append(toIndentedString(endWaitDate)).append("\n");
    sb.append("    remainingTime: ").append(toIndentedString(remainingTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("endWaitDate", "remainingTime"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ControllerWorkflooModelTimer
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ControllerWorkflooModelTimer.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ControllerWorkflooModelTimer is not found in the empty JSON string", ControllerWorkflooModelTimer.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ControllerWorkflooModelTimer.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ControllerWorkflooModelTimer` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("endWaitDate") != null && !jsonObj.get("endWaitDate").isJsonNull()) && !jsonObj.get("endWaitDate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `endWaitDate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("endWaitDate").toString()));
      }
      // validate the optional field `remainingTime`
      if (jsonObj.get("remainingTime") != null && !jsonObj.get("remainingTime").isJsonNull()) {
        ControllerWorkflooModelRemainingTime.validateJsonElement(jsonObj.get("remainingTime"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ControllerWorkflooModelTimer.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ControllerWorkflooModelTimer' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ControllerWorkflooModelTimer> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ControllerWorkflooModelTimer.class));

       return (TypeAdapter<T>) new TypeAdapter<ControllerWorkflooModelTimer>() {
           @Override
           public void write(JsonWriter out, ControllerWorkflooModelTimer value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ControllerWorkflooModelTimer read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ControllerWorkflooModelTimer given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ControllerWorkflooModelTimer
   * @throws IOException if the JSON string is invalid with respect to ControllerWorkflooModelTimer
   */
  public static ControllerWorkflooModelTimer fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ControllerWorkflooModelTimer.class);
  }

  /**
   * Convert an instance of ControllerWorkflooModelTimer to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

