/*
 * Workfloo API
 * API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package kiban.sdk.workfloo.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import kiban.sdk.workfloo.JSON;

/**
 * ControllerWorkflooModelApiHttp
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-10T16:42:49.836741-06:00[America/Mexico_City]", comments = "Generator version: 7.24.0")
public class ControllerWorkflooModelApiHttp {
  public static final String SERIALIZED_NAME_BODY = "body";
  @SerializedName(SERIALIZED_NAME_BODY)
  @javax.annotation.Nullable
  private List<Integer> body = new ArrayList<>();

  public static final String SERIALIZED_NAME_DATE = "date";
  @SerializedName(SERIALIZED_NAME_DATE)
  @javax.annotation.Nullable
  private String date;

  public static final String SERIALIZED_NAME_HEADERS = "headers";
  @SerializedName(SERIALIZED_NAME_HEADERS)
  @javax.annotation.Nullable
  private Map<String, String> headers = new HashMap<>();

  public static final String SERIALIZED_NAME_HTTP_CODE = "httpCode";
  @SerializedName(SERIALIZED_NAME_HTTP_CODE)
  @javax.annotation.Nullable
  private Integer httpCode;

  public static final String SERIALIZED_NAME_QUERY_PARAMS = "queryParams";
  @SerializedName(SERIALIZED_NAME_QUERY_PARAMS)
  @javax.annotation.Nullable
  private Map<String, String> queryParams = new HashMap<>();

  public ControllerWorkflooModelApiHttp() {
  }

  public ControllerWorkflooModelApiHttp body(@javax.annotation.Nullable List<Integer> body) {
    this.body = body;
    return this;
  }

  public ControllerWorkflooModelApiHttp addBodyItem(Integer bodyItem) {
    if (this.body == null) {
      this.body = new ArrayList<>();
    }
    this.body.add(bodyItem);
    return this;
  }

  /**
   * Get body
   * @return body
   */
  @javax.annotation.Nullable
  public List<Integer> getBody() {
    return body;
  }

  public void setBody(@javax.annotation.Nullable List<Integer> body) {
    this.body = body;
  }


  public ControllerWorkflooModelApiHttp date(@javax.annotation.Nullable String date) {
    this.date = date;
    return this;
  }

  /**
   * Get date
   * @return date
   */
  @javax.annotation.Nullable
  public String getDate() {
    return date;
  }

  public void setDate(@javax.annotation.Nullable String date) {
    this.date = date;
  }


  public ControllerWorkflooModelApiHttp headers(@javax.annotation.Nullable Map<String, String> headers) {
    this.headers = headers;
    return this;
  }

  public ControllerWorkflooModelApiHttp putHeadersItem(String key, String headersItem) {
    if (this.headers == null) {
      this.headers = new HashMap<>();
    }
    this.headers.put(key, headersItem);
    return this;
  }

  /**
   * Get headers
   * @return headers
   */
  @javax.annotation.Nullable
  public Map<String, String> getHeaders() {
    return headers;
  }

  public void setHeaders(@javax.annotation.Nullable Map<String, String> headers) {
    this.headers = headers;
  }


  public ControllerWorkflooModelApiHttp httpCode(@javax.annotation.Nullable Integer httpCode) {
    this.httpCode = httpCode;
    return this;
  }

  /**
   * Get httpCode
   * @return httpCode
   */
  @javax.annotation.Nullable
  public Integer getHttpCode() {
    return httpCode;
  }

  public void setHttpCode(@javax.annotation.Nullable Integer httpCode) {
    this.httpCode = httpCode;
  }


  public ControllerWorkflooModelApiHttp queryParams(@javax.annotation.Nullable Map<String, String> queryParams) {
    this.queryParams = queryParams;
    return this;
  }

  public ControllerWorkflooModelApiHttp putQueryParamsItem(String key, String queryParamsItem) {
    if (this.queryParams == null) {
      this.queryParams = new HashMap<>();
    }
    this.queryParams.put(key, queryParamsItem);
    return this;
  }

  /**
   * Get queryParams
   * @return queryParams
   */
  @javax.annotation.Nullable
  public Map<String, String> getQueryParams() {
    return queryParams;
  }

  public void setQueryParams(@javax.annotation.Nullable Map<String, String> queryParams) {
    this.queryParams = queryParams;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ControllerWorkflooModelApiHttp controllerWorkflooModelApiHttp = (ControllerWorkflooModelApiHttp) o;
    return Objects.equals(this.body, controllerWorkflooModelApiHttp.body) &&
        Objects.equals(this.date, controllerWorkflooModelApiHttp.date) &&
        Objects.equals(this.headers, controllerWorkflooModelApiHttp.headers) &&
        Objects.equals(this.httpCode, controllerWorkflooModelApiHttp.httpCode) &&
        Objects.equals(this.queryParams, controllerWorkflooModelApiHttp.queryParams);
  }

  @Override
  public int hashCode() {
    return Objects.hash(body, date, headers, httpCode, queryParams);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ControllerWorkflooModelApiHttp {\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    httpCode: ").append(toIndentedString(httpCode)).append("\n");
    sb.append("    queryParams: ").append(toIndentedString(queryParams)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("body", "date", "headers", "httpCode", "queryParams"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ControllerWorkflooModelApiHttp
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ControllerWorkflooModelApiHttp.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ControllerWorkflooModelApiHttp is not found in the empty JSON string", ControllerWorkflooModelApiHttp.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ControllerWorkflooModelApiHttp.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ControllerWorkflooModelApiHttp` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("body") != null && !jsonObj.get("body").isJsonNull() && !jsonObj.get("body").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `body` to be an array in the JSON string but got `%s`", jsonObj.get("body").toString()));
      }
      if ((jsonObj.get("date") != null && !jsonObj.get("date").isJsonNull()) && !jsonObj.get("date").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `date` to be a primitive type in the JSON string but got `%s`", jsonObj.get("date").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ControllerWorkflooModelApiHttp.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ControllerWorkflooModelApiHttp' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ControllerWorkflooModelApiHttp> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ControllerWorkflooModelApiHttp.class));

       return (TypeAdapter<T>) new TypeAdapter<ControllerWorkflooModelApiHttp>() {
           @Override
           public void write(JsonWriter out, ControllerWorkflooModelApiHttp value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ControllerWorkflooModelApiHttp read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ControllerWorkflooModelApiHttp given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ControllerWorkflooModelApiHttp
   * @throws IOException if the JSON string is invalid with respect to ControllerWorkflooModelApiHttp
   */
  public static ControllerWorkflooModelApiHttp fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ControllerWorkflooModelApiHttp.class);
  }

  /**
   * Convert an instance of ControllerWorkflooModelApiHttp to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

