/*
 * Workfloo API
 * API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hola@kiban.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kiban.workfloo.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kiban.workfloo.model.ControllerWorkflooModelNode;
import com.kiban.workfloo.model.ControllerWorkflooModelNodeResume;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.kiban.workfloo.JSON;

/**
 * ControllerWorkflooModelWorkflooListItem
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class ControllerWorkflooModelWorkflooListItem {
  public static final String SERIALIZED_NAME_CANCELLED_AT = "cancelledAt";
  @SerializedName(SERIALIZED_NAME_CANCELLED_AT)
  @javax.annotation.Nullable
  private String cancelledAt;

  public static final String SERIALIZED_NAME_CANCELLED_BY = "cancelledBy";
  @SerializedName(SERIALIZED_NAME_CANCELLED_BY)
  @javax.annotation.Nullable
  private String cancelledBy;

  public static final String SERIALIZED_NAME_COMPANY_NAME = "companyName";
  @SerializedName(SERIALIZED_NAME_COMPANY_NAME)
  @javax.annotation.Nullable
  private String companyName;

  public static final String SERIALIZED_NAME_CREATED = "created";
  @SerializedName(SERIALIZED_NAME_CREATED)
  @javax.annotation.Nullable
  private String created;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private String createdAt;

  public static final String SERIALIZED_NAME_CREATED_BY = "createdBy";
  @SerializedName(SERIALIZED_NAME_CREATED_BY)
  @javax.annotation.Nullable
  private String createdBy;

  public static final String SERIALIZED_NAME_CURRENT_NODE_NAME = "currentNodeName";
  @SerializedName(SERIALIZED_NAME_CURRENT_NODE_NAME)
  @javax.annotation.Nullable
  private String currentNodeName;

  public static final String SERIALIZED_NAME_FIRST_NAME = "firstName";
  @SerializedName(SERIALIZED_NAME_FIRST_NAME)
  @javax.annotation.Nullable
  private String firstName;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_ID_UNYKOO = "idUnykoo";
  @SerializedName(SERIALIZED_NAME_ID_UNYKOO)
  @javax.annotation.Nullable
  private Integer idUnykoo;

  public static final String SERIALIZED_NAME_IP_ORIGIN = "ipOrigin";
  @SerializedName(SERIALIZED_NAME_IP_ORIGIN)
  @javax.annotation.Nullable
  private String ipOrigin;

  public static final String SERIALIZED_NAME_LABELS = "labels";
  @SerializedName(SERIALIZED_NAME_LABELS)
  @javax.annotation.Nullable
  private List<String> labels;

  public static final String SERIALIZED_NAME_LAST_NAME1 = "lastName1";
  @SerializedName(SERIALIZED_NAME_LAST_NAME1)
  @javax.annotation.Nullable
  private String lastName1;

  public static final String SERIALIZED_NAME_LAST_NAME2 = "lastName2";
  @SerializedName(SERIALIZED_NAME_LAST_NAME2)
  @javax.annotation.Nullable
  private String lastName2;

  public static final String SERIALIZED_NAME_MODIFIED = "modified";
  @SerializedName(SERIALIZED_NAME_MODIFIED)
  @javax.annotation.Nullable
  private String modified;

  public static final String SERIALIZED_NAME_MODIFIED_AT = "modifiedAt";
  @SerializedName(SERIALIZED_NAME_MODIFIED_AT)
  @javax.annotation.Nullable
  private String modifiedAt;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_NODES = "nodes";
  @SerializedName(SERIALIZED_NAME_NODES)
  @javax.annotation.Nullable
  private List<ControllerWorkflooModelNodeResume> nodes;

  public static final String SERIALIZED_NAME_ORIGIN = "origin";
  @SerializedName(SERIALIZED_NAME_ORIGIN)
  @javax.annotation.Nullable
  private String origin;

  public static final String SERIALIZED_NAME_RFC_PF = "rfcPf";
  @SerializedName(SERIALIZED_NAME_RFC_PF)
  @javax.annotation.Nullable
  private String rfcPf;

  public static final String SERIALIZED_NAME_RFC_PM = "rfcPm";
  @SerializedName(SERIALIZED_NAME_RFC_PM)
  @javax.annotation.Nullable
  private String rfcPm;

  public static final String SERIALIZED_NAME_SCENERY_ID = "sceneryId";
  @SerializedName(SERIALIZED_NAME_SCENERY_ID)
  @javax.annotation.Nullable
  private String sceneryId;

  public static final String SERIALIZED_NAME_SCENERY_NAME = "sceneryName";
  @SerializedName(SERIALIZED_NAME_SCENERY_NAME)
  @javax.annotation.Nullable
  private String sceneryName;

  public static final String SERIALIZED_NAME_SECOND_NAME = "secondName";
  @SerializedName(SERIALIZED_NAME_SECOND_NAME)
  @javax.annotation.Nullable
  private String secondName;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private String status;

  public static final String SERIALIZED_NAME_STEPS = "steps";
  @SerializedName(SERIALIZED_NAME_STEPS)
  @javax.annotation.Nullable
  private List<ControllerWorkflooModelNode> steps;

  public ControllerWorkflooModelWorkflooListItem() {
  }

  public ControllerWorkflooModelWorkflooListItem cancelledAt(@javax.annotation.Nullable String cancelledAt) {
    this.cancelledAt = cancelledAt;
    return this;
  }

  /**
   * Get cancelledAt
   * @return cancelledAt
   */
  @javax.annotation.Nullable
  public String getCancelledAt() {
    return cancelledAt;
  }

  public void setCancelledAt(@javax.annotation.Nullable String cancelledAt) {
    this.cancelledAt = cancelledAt;
  }


  public ControllerWorkflooModelWorkflooListItem cancelledBy(@javax.annotation.Nullable String cancelledBy) {
    this.cancelledBy = cancelledBy;
    return this;
  }

  /**
   * Get cancelledBy
   * @return cancelledBy
   */
  @javax.annotation.Nullable
  public String getCancelledBy() {
    return cancelledBy;
  }

  public void setCancelledBy(@javax.annotation.Nullable String cancelledBy) {
    this.cancelledBy = cancelledBy;
  }


  public ControllerWorkflooModelWorkflooListItem companyName(@javax.annotation.Nullable String companyName) {
    this.companyName = companyName;
    return this;
  }

  /**
   * Get companyName
   * @return companyName
   */
  @javax.annotation.Nullable
  public String getCompanyName() {
    return companyName;
  }

  public void setCompanyName(@javax.annotation.Nullable String companyName) {
    this.companyName = companyName;
  }


  public ControllerWorkflooModelWorkflooListItem created(@javax.annotation.Nullable String created) {
    this.created = created;
    return this;
  }

  /**
   * Ejecución completa (content&#x3D;true): lo mismo que GET /api/v1/workfloo/{id}.
   * @return created
   */
  @javax.annotation.Nullable
  public String getCreated() {
    return created;
  }

  public void setCreated(@javax.annotation.Nullable String created) {
    this.created = created;
  }


  public ControllerWorkflooModelWorkflooListItem createdAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Resumen (content&#x3D;false).
   * @return createdAt
   */
  @javax.annotation.Nullable
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
  }


  public ControllerWorkflooModelWorkflooListItem createdBy(@javax.annotation.Nullable String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

  /**
   * Get createdBy
   * @return createdBy
   */
  @javax.annotation.Nullable
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(@javax.annotation.Nullable String createdBy) {
    this.createdBy = createdBy;
  }


  public ControllerWorkflooModelWorkflooListItem currentNodeName(@javax.annotation.Nullable String currentNodeName) {
    this.currentNodeName = currentNodeName;
    return this;
  }

  /**
   * Get currentNodeName
   * @return currentNodeName
   */
  @javax.annotation.Nullable
  public String getCurrentNodeName() {
    return currentNodeName;
  }

  public void setCurrentNodeName(@javax.annotation.Nullable String currentNodeName) {
    this.currentNodeName = currentNodeName;
  }


  public ControllerWorkflooModelWorkflooListItem firstName(@javax.annotation.Nullable String firstName) {
    this.firstName = firstName;
    return this;
  }

  /**
   * Get firstName
   * @return firstName
   */
  @javax.annotation.Nullable
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(@javax.annotation.Nullable String firstName) {
    this.firstName = firstName;
  }


  public ControllerWorkflooModelWorkflooListItem id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Comunes a las dos formas.
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public ControllerWorkflooModelWorkflooListItem idUnykoo(@javax.annotation.Nullable Integer idUnykoo) {
    this.idUnykoo = idUnykoo;
    return this;
  }

  /**
   * Get idUnykoo
   * @return idUnykoo
   */
  @javax.annotation.Nullable
  public Integer getIdUnykoo() {
    return idUnykoo;
  }

  public void setIdUnykoo(@javax.annotation.Nullable Integer idUnykoo) {
    this.idUnykoo = idUnykoo;
  }


  public ControllerWorkflooModelWorkflooListItem ipOrigin(@javax.annotation.Nullable String ipOrigin) {
    this.ipOrigin = ipOrigin;
    return this;
  }

  /**
   * Get ipOrigin
   * @return ipOrigin
   */
  @javax.annotation.Nullable
  public String getIpOrigin() {
    return ipOrigin;
  }

  public void setIpOrigin(@javax.annotation.Nullable String ipOrigin) {
    this.ipOrigin = ipOrigin;
  }


  public ControllerWorkflooModelWorkflooListItem labels(@javax.annotation.Nullable List<String> labels) {
    this.labels = labels;
    return this;
  }

  public ControllerWorkflooModelWorkflooListItem addLabelsItem(String labelsItem) {
    if (this.labels == null) {
      this.labels = new ArrayList<>();
    }
    this.labels.add(labelsItem);
    return this;
  }

  /**
   * Get labels
   * @return labels
   */
  @javax.annotation.Nullable
  public List<String> getLabels() {
    return labels;
  }

  public void setLabels(@javax.annotation.Nullable List<String> labels) {
    this.labels = labels;
  }


  public ControllerWorkflooModelWorkflooListItem lastName1(@javax.annotation.Nullable String lastName1) {
    this.lastName1 = lastName1;
    return this;
  }

  /**
   * Get lastName1
   * @return lastName1
   */
  @javax.annotation.Nullable
  public String getLastName1() {
    return lastName1;
  }

  public void setLastName1(@javax.annotation.Nullable String lastName1) {
    this.lastName1 = lastName1;
  }


  public ControllerWorkflooModelWorkflooListItem lastName2(@javax.annotation.Nullable String lastName2) {
    this.lastName2 = lastName2;
    return this;
  }

  /**
   * Get lastName2
   * @return lastName2
   */
  @javax.annotation.Nullable
  public String getLastName2() {
    return lastName2;
  }

  public void setLastName2(@javax.annotation.Nullable String lastName2) {
    this.lastName2 = lastName2;
  }


  public ControllerWorkflooModelWorkflooListItem modified(@javax.annotation.Nullable String modified) {
    this.modified = modified;
    return this;
  }

  /**
   * Get modified
   * @return modified
   */
  @javax.annotation.Nullable
  public String getModified() {
    return modified;
  }

  public void setModified(@javax.annotation.Nullable String modified) {
    this.modified = modified;
  }


  public ControllerWorkflooModelWorkflooListItem modifiedAt(@javax.annotation.Nullable String modifiedAt) {
    this.modifiedAt = modifiedAt;
    return this;
  }

  /**
   * Get modifiedAt
   * @return modifiedAt
   */
  @javax.annotation.Nullable
  public String getModifiedAt() {
    return modifiedAt;
  }

  public void setModifiedAt(@javax.annotation.Nullable String modifiedAt) {
    this.modifiedAt = modifiedAt;
  }


  public ControllerWorkflooModelWorkflooListItem name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public ControllerWorkflooModelWorkflooListItem nodes(@javax.annotation.Nullable List<ControllerWorkflooModelNodeResume> nodes) {
    this.nodes = nodes;
    return this;
  }

  public ControllerWorkflooModelWorkflooListItem addNodesItem(ControllerWorkflooModelNodeResume nodesItem) {
    if (this.nodes == null) {
      this.nodes = new ArrayList<>();
    }
    this.nodes.add(nodesItem);
    return this;
  }

  /**
   * Get nodes
   * @return nodes
   */
  @javax.annotation.Nullable
  public List<ControllerWorkflooModelNodeResume> getNodes() {
    return nodes;
  }

  public void setNodes(@javax.annotation.Nullable List<ControllerWorkflooModelNodeResume> nodes) {
    this.nodes = nodes;
  }


  public ControllerWorkflooModelWorkflooListItem origin(@javax.annotation.Nullable String origin) {
    this.origin = origin;
    return this;
  }

  /**
   * Get origin
   * @return origin
   */
  @javax.annotation.Nullable
  public String getOrigin() {
    return origin;
  }

  public void setOrigin(@javax.annotation.Nullable String origin) {
    this.origin = origin;
  }


  public ControllerWorkflooModelWorkflooListItem rfcPf(@javax.annotation.Nullable String rfcPf) {
    this.rfcPf = rfcPf;
    return this;
  }

  /**
   * Get rfcPf
   * @return rfcPf
   */
  @javax.annotation.Nullable
  public String getRfcPf() {
    return rfcPf;
  }

  public void setRfcPf(@javax.annotation.Nullable String rfcPf) {
    this.rfcPf = rfcPf;
  }


  public ControllerWorkflooModelWorkflooListItem rfcPm(@javax.annotation.Nullable String rfcPm) {
    this.rfcPm = rfcPm;
    return this;
  }

  /**
   * Get rfcPm
   * @return rfcPm
   */
  @javax.annotation.Nullable
  public String getRfcPm() {
    return rfcPm;
  }

  public void setRfcPm(@javax.annotation.Nullable String rfcPm) {
    this.rfcPm = rfcPm;
  }


  public ControllerWorkflooModelWorkflooListItem sceneryId(@javax.annotation.Nullable String sceneryId) {
    this.sceneryId = sceneryId;
    return this;
  }

  /**
   * Get sceneryId
   * @return sceneryId
   */
  @javax.annotation.Nullable
  public String getSceneryId() {
    return sceneryId;
  }

  public void setSceneryId(@javax.annotation.Nullable String sceneryId) {
    this.sceneryId = sceneryId;
  }


  public ControllerWorkflooModelWorkflooListItem sceneryName(@javax.annotation.Nullable String sceneryName) {
    this.sceneryName = sceneryName;
    return this;
  }

  /**
   * Get sceneryName
   * @return sceneryName
   */
  @javax.annotation.Nullable
  public String getSceneryName() {
    return sceneryName;
  }

  public void setSceneryName(@javax.annotation.Nullable String sceneryName) {
    this.sceneryName = sceneryName;
  }


  public ControllerWorkflooModelWorkflooListItem secondName(@javax.annotation.Nullable String secondName) {
    this.secondName = secondName;
    return this;
  }

  /**
   * Get secondName
   * @return secondName
   */
  @javax.annotation.Nullable
  public String getSecondName() {
    return secondName;
  }

  public void setSecondName(@javax.annotation.Nullable String secondName) {
    this.secondName = secondName;
  }


  public ControllerWorkflooModelWorkflooListItem status(@javax.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  public String getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }


  public ControllerWorkflooModelWorkflooListItem steps(@javax.annotation.Nullable List<ControllerWorkflooModelNode> steps) {
    this.steps = steps;
    return this;
  }

  public ControllerWorkflooModelWorkflooListItem addStepsItem(ControllerWorkflooModelNode stepsItem) {
    if (this.steps == null) {
      this.steps = new ArrayList<>();
    }
    this.steps.add(stepsItem);
    return this;
  }

  /**
   * Get steps
   * @return steps
   */
  @javax.annotation.Nullable
  public List<ControllerWorkflooModelNode> getSteps() {
    return steps;
  }

  public void setSteps(@javax.annotation.Nullable List<ControllerWorkflooModelNode> steps) {
    this.steps = steps;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ControllerWorkflooModelWorkflooListItem controllerWorkflooModelWorkflooListItem = (ControllerWorkflooModelWorkflooListItem) o;
    return Objects.equals(this.cancelledAt, controllerWorkflooModelWorkflooListItem.cancelledAt) &&
        Objects.equals(this.cancelledBy, controllerWorkflooModelWorkflooListItem.cancelledBy) &&
        Objects.equals(this.companyName, controllerWorkflooModelWorkflooListItem.companyName) &&
        Objects.equals(this.created, controllerWorkflooModelWorkflooListItem.created) &&
        Objects.equals(this.createdAt, controllerWorkflooModelWorkflooListItem.createdAt) &&
        Objects.equals(this.createdBy, controllerWorkflooModelWorkflooListItem.createdBy) &&
        Objects.equals(this.currentNodeName, controllerWorkflooModelWorkflooListItem.currentNodeName) &&
        Objects.equals(this.firstName, controllerWorkflooModelWorkflooListItem.firstName) &&
        Objects.equals(this.id, controllerWorkflooModelWorkflooListItem.id) &&
        Objects.equals(this.idUnykoo, controllerWorkflooModelWorkflooListItem.idUnykoo) &&
        Objects.equals(this.ipOrigin, controllerWorkflooModelWorkflooListItem.ipOrigin) &&
        Objects.equals(this.labels, controllerWorkflooModelWorkflooListItem.labels) &&
        Objects.equals(this.lastName1, controllerWorkflooModelWorkflooListItem.lastName1) &&
        Objects.equals(this.lastName2, controllerWorkflooModelWorkflooListItem.lastName2) &&
        Objects.equals(this.modified, controllerWorkflooModelWorkflooListItem.modified) &&
        Objects.equals(this.modifiedAt, controllerWorkflooModelWorkflooListItem.modifiedAt) &&
        Objects.equals(this.name, controllerWorkflooModelWorkflooListItem.name) &&
        Objects.equals(this.nodes, controllerWorkflooModelWorkflooListItem.nodes) &&
        Objects.equals(this.origin, controllerWorkflooModelWorkflooListItem.origin) &&
        Objects.equals(this.rfcPf, controllerWorkflooModelWorkflooListItem.rfcPf) &&
        Objects.equals(this.rfcPm, controllerWorkflooModelWorkflooListItem.rfcPm) &&
        Objects.equals(this.sceneryId, controllerWorkflooModelWorkflooListItem.sceneryId) &&
        Objects.equals(this.sceneryName, controllerWorkflooModelWorkflooListItem.sceneryName) &&
        Objects.equals(this.secondName, controllerWorkflooModelWorkflooListItem.secondName) &&
        Objects.equals(this.status, controllerWorkflooModelWorkflooListItem.status) &&
        Objects.equals(this.steps, controllerWorkflooModelWorkflooListItem.steps);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(cancelledAt, cancelledBy, companyName, created, createdAt, createdBy, currentNodeName, firstName, id, idUnykoo, ipOrigin, labels, lastName1, lastName2, modified, modifiedAt, name, nodes, origin, rfcPf, rfcPm, sceneryId, sceneryName, secondName, status, steps);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ControllerWorkflooModelWorkflooListItem {\n");
    sb.append("    cancelledAt: ").append(toIndentedString(cancelledAt)).append("\n");
    sb.append("    cancelledBy: ").append(toIndentedString(cancelledBy)).append("\n");
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    currentNodeName: ").append(toIndentedString(currentNodeName)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    idUnykoo: ").append(toIndentedString(idUnykoo)).append("\n");
    sb.append("    ipOrigin: ").append(toIndentedString(ipOrigin)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    lastName1: ").append(toIndentedString(lastName1)).append("\n");
    sb.append("    lastName2: ").append(toIndentedString(lastName2)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    modifiedAt: ").append(toIndentedString(modifiedAt)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nodes: ").append(toIndentedString(nodes)).append("\n");
    sb.append("    origin: ").append(toIndentedString(origin)).append("\n");
    sb.append("    rfcPf: ").append(toIndentedString(rfcPf)).append("\n");
    sb.append("    rfcPm: ").append(toIndentedString(rfcPm)).append("\n");
    sb.append("    sceneryId: ").append(toIndentedString(sceneryId)).append("\n");
    sb.append("    sceneryName: ").append(toIndentedString(sceneryName)).append("\n");
    sb.append("    secondName: ").append(toIndentedString(secondName)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    steps: ").append(toIndentedString(steps)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("cancelledAt", "cancelledBy", "companyName", "created", "createdAt", "createdBy", "currentNodeName", "firstName", "id", "idUnykoo", "ipOrigin", "labels", "lastName1", "lastName2", "modified", "modifiedAt", "name", "nodes", "origin", "rfcPf", "rfcPm", "sceneryId", "sceneryName", "secondName", "status", "steps"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ControllerWorkflooModelWorkflooListItem
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ControllerWorkflooModelWorkflooListItem.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ControllerWorkflooModelWorkflooListItem is not found in the empty JSON string", ControllerWorkflooModelWorkflooListItem.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ControllerWorkflooModelWorkflooListItem.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ControllerWorkflooModelWorkflooListItem` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("cancelledAt") != null && !jsonObj.get("cancelledAt").isJsonNull()) && !jsonObj.get("cancelledAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `cancelledAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cancelledAt").toString()));
      }
      if ((jsonObj.get("cancelledBy") != null && !jsonObj.get("cancelledBy").isJsonNull()) && !jsonObj.get("cancelledBy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `cancelledBy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cancelledBy").toString()));
      }
      if ((jsonObj.get("companyName") != null && !jsonObj.get("companyName").isJsonNull()) && !jsonObj.get("companyName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `companyName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("companyName").toString()));
      }
      if ((jsonObj.get("created") != null && !jsonObj.get("created").isJsonNull()) && !jsonObj.get("created").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `created` to be a primitive type in the JSON string but got `%s`", jsonObj.get("created").toString()));
      }
      if ((jsonObj.get("createdAt") != null && !jsonObj.get("createdAt").isJsonNull()) && !jsonObj.get("createdAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `createdAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("createdAt").toString()));
      }
      if ((jsonObj.get("createdBy") != null && !jsonObj.get("createdBy").isJsonNull()) && !jsonObj.get("createdBy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `createdBy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("createdBy").toString()));
      }
      if ((jsonObj.get("currentNodeName") != null && !jsonObj.get("currentNodeName").isJsonNull()) && !jsonObj.get("currentNodeName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `currentNodeName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("currentNodeName").toString()));
      }
      if ((jsonObj.get("firstName") != null && !jsonObj.get("firstName").isJsonNull()) && !jsonObj.get("firstName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `firstName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("firstName").toString()));
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("ipOrigin") != null && !jsonObj.get("ipOrigin").isJsonNull()) && !jsonObj.get("ipOrigin").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `ipOrigin` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ipOrigin").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("labels") != null && !jsonObj.get("labels").isJsonNull() && !jsonObj.get("labels").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `labels` to be an array in the JSON string but got `%s`", jsonObj.get("labels").toString()));
      }
      if ((jsonObj.get("lastName1") != null && !jsonObj.get("lastName1").isJsonNull()) && !jsonObj.get("lastName1").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `lastName1` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lastName1").toString()));
      }
      if ((jsonObj.get("lastName2") != null && !jsonObj.get("lastName2").isJsonNull()) && !jsonObj.get("lastName2").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `lastName2` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lastName2").toString()));
      }
      if ((jsonObj.get("modified") != null && !jsonObj.get("modified").isJsonNull()) && !jsonObj.get("modified").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `modified` to be a primitive type in the JSON string but got `%s`", jsonObj.get("modified").toString()));
      }
      if ((jsonObj.get("modifiedAt") != null && !jsonObj.get("modifiedAt").isJsonNull()) && !jsonObj.get("modifiedAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `modifiedAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("modifiedAt").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (jsonObj.get("nodes") != null && !jsonObj.get("nodes").isJsonNull()) {
        JsonArray jsonArraynodes = jsonObj.getAsJsonArray("nodes");
        if (jsonArraynodes != null) {
          // ensure the json data is an array
          if (!jsonObj.get("nodes").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `nodes` to be an array in the JSON string but got `%s`", jsonObj.get("nodes").toString()));
          }

          // validate the optional field `nodes` (array)
          for (int i = 0; i < jsonArraynodes.size(); i++) {
            ControllerWorkflooModelNodeResume.validateJsonElement(jsonArraynodes.get(i));
          };
        }
      }
      if ((jsonObj.get("origin") != null && !jsonObj.get("origin").isJsonNull()) && !jsonObj.get("origin").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `origin` to be a primitive type in the JSON string but got `%s`", jsonObj.get("origin").toString()));
      }
      if ((jsonObj.get("rfcPf") != null && !jsonObj.get("rfcPf").isJsonNull()) && !jsonObj.get("rfcPf").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `rfcPf` to be a primitive type in the JSON string but got `%s`", jsonObj.get("rfcPf").toString()));
      }
      if ((jsonObj.get("rfcPm") != null && !jsonObj.get("rfcPm").isJsonNull()) && !jsonObj.get("rfcPm").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `rfcPm` to be a primitive type in the JSON string but got `%s`", jsonObj.get("rfcPm").toString()));
      }
      if ((jsonObj.get("sceneryId") != null && !jsonObj.get("sceneryId").isJsonNull()) && !jsonObj.get("sceneryId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `sceneryId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sceneryId").toString()));
      }
      if ((jsonObj.get("sceneryName") != null && !jsonObj.get("sceneryName").isJsonNull()) && !jsonObj.get("sceneryName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `sceneryName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sceneryName").toString()));
      }
      if ((jsonObj.get("secondName") != null && !jsonObj.get("secondName").isJsonNull()) && !jsonObj.get("secondName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `secondName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("secondName").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if (jsonObj.get("steps") != null && !jsonObj.get("steps").isJsonNull()) {
        JsonArray jsonArraysteps = jsonObj.getAsJsonArray("steps");
        if (jsonArraysteps != null) {
          // ensure the json data is an array
          if (!jsonObj.get("steps").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `steps` to be an array in the JSON string but got `%s`", jsonObj.get("steps").toString()));
          }

          // validate the optional field `steps` (array)
          for (int i = 0; i < jsonArraysteps.size(); i++) {
            ControllerWorkflooModelNode.validateJsonElement(jsonArraysteps.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ControllerWorkflooModelWorkflooListItem.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ControllerWorkflooModelWorkflooListItem' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ControllerWorkflooModelWorkflooListItem> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ControllerWorkflooModelWorkflooListItem.class));

       return (TypeAdapter<T>) new TypeAdapter<ControllerWorkflooModelWorkflooListItem>() {
           @Override
           public void write(JsonWriter out, ControllerWorkflooModelWorkflooListItem value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ControllerWorkflooModelWorkflooListItem read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ControllerWorkflooModelWorkflooListItem given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ControllerWorkflooModelWorkflooListItem
   * @throws IOException if the JSON string is invalid with respect to ControllerWorkflooModelWorkflooListItem
   */
  public static ControllerWorkflooModelWorkflooListItem fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ControllerWorkflooModelWorkflooListItem.class);
  }

  /**
   * Convert an instance of ControllerWorkflooModelWorkflooListItem to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

