/*
 * Workfloo API
 *
 * API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kiban.Workfloo.Model;
using Kiban.Workfloo.Client;
using System.Reflection;

namespace Kiban.Workfloo.Test.Model
{
    /// <summary>
    ///  Class for testing ControllerWorkflooModelOtpValidateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ControllerWorkflooModelOtpValidateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ControllerWorkflooModelOtpValidateRequest
        //private ControllerWorkflooModelOtpValidateRequest instance;

        public ControllerWorkflooModelOtpValidateRequestTests()
        {
            // TODO uncomment below to create an instance of ControllerWorkflooModelOtpValidateRequest
            //instance = new ControllerWorkflooModelOtpValidateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ControllerWorkflooModelOtpValidateRequest
        /// </summary>
        [Fact]
        public void ControllerWorkflooModelOtpValidateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ControllerWorkflooModelOtpValidateRequest
            //Assert.IsType<ControllerWorkflooModelOtpValidateRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Fact]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }
    }
}
