/*
 * Workfloo API
 * API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package kiban.sdk.workfloo.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import kiban.sdk.workfloo.model.ControllerWorkflooModelReviewResume;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ControllerWorkflooModelValidationResume
 */
public class ControllerWorkflooModelValidationResumeTest {
    private final ControllerWorkflooModelValidationResume model = new ControllerWorkflooModelValidationResume();

    /**
     * Model tests for ControllerWorkflooModelValidationResume
     */
    @Test
    public void testControllerWorkflooModelValidationResume() {
        // TODO: test ControllerWorkflooModelValidationResume
    }

    /**
     * Test the property 'decision'
     */
    @Test
    public void decisionTest() {
        // TODO: test decision
    }

    /**
     * Test the property 'reviewedAt'
     */
    @Test
    public void reviewedAtTest() {
        // TODO: test reviewedAt
    }

    /**
     * Test the property 'reviewedBy'
     */
    @Test
    public void reviewedByTest() {
        // TODO: test reviewedBy
    }

    /**
     * Test the property 'reviewerNote'
     */
    @Test
    public void reviewerNoteTest() {
        // TODO: test reviewerNote
    }

    /**
     * Test the property 'reviews'
     */
    @Test
    public void reviewsTest() {
        // TODO: test reviews
    }

}
