/*
 * Workfloo API
 * API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package kiban.sdk.workfloo.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ControllerWorkflooDefinitionModelFileMetadata
 */
public class ControllerWorkflooDefinitionModelFileMetadataTest {
    private final ControllerWorkflooDefinitionModelFileMetadata model = new ControllerWorkflooDefinitionModelFileMetadata();

    /**
     * Model tests for ControllerWorkflooDefinitionModelFileMetadata
     */
    @Test
    public void testControllerWorkflooDefinitionModelFileMetadata() {
        // TODO: test ControllerWorkflooDefinitionModelFileMetadata
    }

    /**
     * Test the property 'formats'
     */
    @Test
    public void formatsTest() {
        // TODO: test formats
    }

    /**
     * Test the property 'max'
     */
    @Test
    public void maxTest() {
        // TODO: test max
    }

    /**
     * Test the property 'maxSize'
     */
    @Test
    public void maxSizeTest() {
        // TODO: test maxSize
    }

    /**
     * Test the property 'min'
     */
    @Test
    public void minTest() {
        // TODO: test min
    }

}
