/*
 * Workfloo API
 * API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package kiban.sdk.workfloo.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import kiban.sdk.workfloo.model.ControllerWorkflooModelApiData;
import kiban.sdk.workfloo.model.ControllerWorkflooModelData;
import kiban.sdk.workfloo.model.ControllerWorkflooModelDecisionTree;
import kiban.sdk.workfloo.model.ControllerWorkflooModelDocumentsResume;
import kiban.sdk.workfloo.model.ControllerWorkflooModelFile;
import kiban.sdk.workfloo.model.ControllerWorkflooModelFormResume;
import kiban.sdk.workfloo.model.ControllerWorkflooModelLabel;
import kiban.sdk.workfloo.model.ControllerWorkflooModelLinkResume;
import kiban.sdk.workfloo.model.ControllerWorkflooModelNodeDetail;
import kiban.sdk.workfloo.model.ControllerWorkflooModelPdf;
import kiban.sdk.workfloo.model.ControllerWorkflooModelRuleset;
import kiban.sdk.workfloo.model.ControllerWorkflooModelTimer;
import kiban.sdk.workfloo.model.ControllerWorkflooModelValidationResume;
import kiban.sdk.workfloo.model.ControllerWorkflooModelVariable;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ControllerWorkflooModelNodeResume
 */
public class ControllerWorkflooModelNodeResumeTest {
    private final ControllerWorkflooModelNodeResume model = new ControllerWorkflooModelNodeResume();

    /**
     * Model tests for ControllerWorkflooModelNodeResume
     */
    @Test
    public void testControllerWorkflooModelNodeResume() {
        // TODO: test ControllerWorkflooModelNodeResume
    }

    /**
     * Test the property 'apiData'
     */
    @Test
    public void apiDataTest() {
        // TODO: test apiData
    }

    /**
     * Test the property 'created'
     */
    @Test
    public void createdTest() {
        // TODO: test created
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'decisionTree'
     */
    @Test
    public void decisionTreeTest() {
        // TODO: test decisionTree
    }

    /**
     * Test the property 'detail'
     */
    @Test
    public void detailTest() {
        // TODO: test detail
    }

    /**
     * Test the property 'documents'
     */
    @Test
    public void documentsTest() {
        // TODO: test documents
    }

    /**
     * Test the property 'files'
     */
    @Test
    public void filesTest() {
        // TODO: test files
    }

    /**
     * Test the property 'form'
     */
    @Test
    public void formTest() {
        // TODO: test form
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property 'link'
     */
    @Test
    public void linkTest() {
        // TODO: test link
    }

    /**
     * Test the property 'modified'
     */
    @Test
    public void modifiedTest() {
        // TODO: test modified
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'pdf'
     */
    @Test
    public void pdfTest() {
        // TODO: test pdf
    }

    /**
     * Test the property 'request'
     */
    @Test
    public void requestTest() {
        // TODO: test request
    }

    /**
     * Test the property 'response'
     */
    @Test
    public void responseTest() {
        // TODO: test response
    }

    /**
     * Test the property 'ruleset'
     */
    @Test
    public void rulesetTest() {
        // TODO: test ruleset
    }

    /**
     * Test the property 'timer'
     */
    @Test
    public void timerTest() {
        // TODO: test timer
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'validation'
     */
    @Test
    public void validationTest() {
        // TODO: test validation
    }

    /**
     * Test the property 'variables'
     */
    @Test
    public void variablesTest() {
        // TODO: test variables
    }

}
