/*
 * Workfloo API
 * API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package kiban.sdk.workfloo.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import kiban.sdk.workfloo.model.ControllerWorkflooDefinitionModelAutoFilledBy;
import kiban.sdk.workfloo.model.ControllerWorkflooDefinitionModelShow;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ControllerWorkflooDefinitionModelFieldMetadata
 */
public class ControllerWorkflooDefinitionModelFieldMetadataTest {
    private final ControllerWorkflooDefinitionModelFieldMetadata model = new ControllerWorkflooDefinitionModelFieldMetadata();

    /**
     * Model tests for ControllerWorkflooDefinitionModelFieldMetadata
     */
    @Test
    public void testControllerWorkflooDefinitionModelFieldMetadata() {
        // TODO: test ControllerWorkflooDefinitionModelFieldMetadata
    }

    /**
     * Test the property 'autoFilledBy'
     */
    @Test
    public void autoFilledByTest() {
        // TODO: test autoFilledBy
    }

    /**
     * Test the property 'autofillNodeId'
     */
    @Test
    public void autofillNodeIdTest() {
        // TODO: test autofillNodeId
    }

    /**
     * Test the property 'defaultValue'
     */
    @Test
    public void defaultValueTest() {
        // TODO: test defaultValue
    }

    /**
     * Test the property 'html'
     */
    @Test
    public void htmlTest() {
        // TODO: test html
    }

    /**
     * Test the property 'map'
     */
    @Test
    public void mapTest() {
        // TODO: test map
    }

    /**
     * Test the property 'max'
     */
    @Test
    public void maxTest() {
        // TODO: test max
    }

    /**
     * Test the property 'maxLength'
     */
    @Test
    public void maxLengthTest() {
        // TODO: test maxLength
    }

    /**
     * Test the property 'maxVal'
     */
    @Test
    public void maxValTest() {
        // TODO: test maxVal
    }

    /**
     * Test the property 'min'
     */
    @Test
    public void minTest() {
        // TODO: test min
    }

    /**
     * Test the property 'minLength'
     */
    @Test
    public void minLengthTest() {
        // TODO: test minLength
    }

    /**
     * Test the property 'minVal'
     */
    @Test
    public void minValTest() {
        // TODO: test minVal
    }

    /**
     * Test the property 'regex'
     */
    @Test
    public void regexTest() {
        // TODO: test regex
    }

    /**
     * Test the property 'regexMessage'
     */
    @Test
    public void regexMessageTest() {
        // TODO: test regexMessage
    }

    /**
     * Test the property 'show'
     */
    @Test
    public void showTest() {
        // TODO: test show
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
