# coding: utf-8

"""
    Workfloo API

    API pública de Workfloo: ejecuta un workfloo, consulta su estatus y revisa el historial/detalle de ejecuciones. Todos los endpoints se autentican con el header x-api-key.  Ambientes: producción en https://workfloo.kiban.com y sandbox en https://sandbox.workfloo.kiban.com. El host sandbox activa ese modo de forma implícita y tiene precedencia: ahí el query param sandbox se ignora. Desde el host de producción se puede forzar el modo sandbox por request con sandbox=true.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from kiban.sdk.workfloo.models.controller_workfloo_model_event import ControllerWorkflooModelEvent
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ControllerWorkflooModelLinkNipStatus(BaseModel):
    """
    ControllerWorkflooModelLinkNipStatus
    """ # noqa: E501
    company_name: Optional[StrictStr] = Field(default=None, alias="companyName")
    country_code: Optional[StrictStr] = Field(default=None, alias="countryCode")
    email: Optional[StrictStr] = None
    events: Optional[List[ControllerWorkflooModelEvent]] = None
    key: Optional[StrictStr] = None
    key_type_node: Optional[StrictStr] = Field(default=None, alias="keyTypeNode")
    nip_type: Optional[StrictStr] = Field(default=None, alias="nipType")
    phase: Optional[StrictStr] = None
    phone_number: Optional[StrictStr] = Field(default=None, alias="phoneNumber")
    privacy_notice: Optional[StrictStr] = Field(default=None, alias="privacyNotice")
    terms: Optional[StrictStr] = None
    widget: Optional[Any] = None
    __properties: ClassVar[List[str]] = ["companyName", "countryCode", "email", "events", "key", "keyTypeNode", "nipType", "phase", "phoneNumber", "privacyNotice", "terms", "widget"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ControllerWorkflooModelLinkNipStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in events (list)
        _items = []
        if self.events:
            for _item_events in self.events:
                if _item_events:
                    _items.append(_item_events.to_dict())
            _dict['events'] = _items
        # set to None if widget (nullable) is None
        # and model_fields_set contains the field
        if self.widget is None and "widget" in self.model_fields_set:
            _dict['widget'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ControllerWorkflooModelLinkNipStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "companyName": obj.get("companyName"),
            "countryCode": obj.get("countryCode"),
            "email": obj.get("email"),
            "events": [ControllerWorkflooModelEvent.from_dict(_item) for _item in obj["events"]] if obj.get("events") is not None else None,
            "key": obj.get("key"),
            "keyTypeNode": obj.get("keyTypeNode"),
            "nipType": obj.get("nipType"),
            "phase": obj.get("phase"),
            "phoneNumber": obj.get("phoneNumber"),
            "privacyNotice": obj.get("privacyNotice"),
            "terms": obj.get("terms"),
            "widget": obj.get("widget")
        })
        return _obj


